# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 19:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessType',
            fields=[
                ('process_type_id', models.AutoField(db_column='process_type_id', primary_key=True, serialize=False, verbose_name='ProcessTypeID')),
                ('base_process_type_id', models.ForeignKey(blank=True, db_column='base_process_type_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='process.ProcessType', verbose_name='BaseProcessTypeID')),
            ],
            options={
                'db_table': 'process_type',
            },
        ),
    ]
