# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processtype',
            name='sequence_number',
            field=models.IntegerField(db_column='sequence_number', default=0, verbose_name='SequenceNumber'),
        ),
    ]
