# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0002_processtype_sequence_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='processtype',
            name='process_type_tag',
            field=models.CharField(db_column='process_type_tag', default='', max_length=50, verbose_name='ProcessTypeTag'),
        ),
    ]
