# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0003_processtype_process_type_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='processtype',
            name='description',
            field=models.CharField(db_column='description', default='', max_length=100, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='processtype',
            name='notes',
            field=models.CharField(blank=True, db_column='notes', max_length=250, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='processtype',
            name='process_handler',
            field=models.CharField(blank=True, db_column='process_handler', max_length=100, null=True, verbose_name='ProcessHandler'),
        ),
    ]
