# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0004_auto_20170914_2040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processtype',
            name='process_handler',
        ),
        migrations.AddField(
            model_name='processtype',
            name='execution_handler',
            field=models.CharField(blank=True, db_column='execution_handler', max_length=100, null=True, verbose_name='ExecutionHandler'),
        ),
    ]
