# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 19:45
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0005_auto_20170914_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='processtype',
            name='configuration',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, db_column='configuration', null=True, verbose_name='Configuration'),
        ),
        migrations.AddField(
            model_name='processtype',
            name='run_item_units',
            field=models.CharField(blank=True, db_column='run_item_units', max_length=50, null=True, verbose_name='RunItemUnits'),
        ),
        migrations.AlterUniqueTogether(
            name='processtype',
            unique_together=set([('base_process_type_id', 'process_type_tag'), ('base_process_type_id', 'description'), ('base_process_type_id', 'sequence_number')]),
        ),
    ]
