# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 19:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0006_auto_20170914_2045'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessTypeJSONDataSetType',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('process_type_id', models.ForeignKey(db_column='process_type_id', default=0, on_delete=django.db.models.deletion.CASCADE, to='process.ProcessType', verbose_name='ProcessTypeID')),
            ],
            options={
                'db_table': 'process_type_json_data_set_type',
            },
        ),
    ]
