# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 19:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('json_data', '0011_auto_20170914_2025'),
        ('process', '0007_processtypejsondatasettype'),
    ]

    operations = [
        migrations.AddField(
            model_name='processtypejsondatasettype',
            name='data_set_type_id',
            field=models.ForeignKey(db_column='data_set_type_id', default=0, on_delete=django.db.models.deletion.CASCADE, to='json_data.JSONDataSetType', verbose_name='DataSetTypeID'),
        ),
        migrations.AlterUniqueTogether(
            name='processtypejsondatasettype',
            unique_together=set([('process_type_id', 'data_set_type_id')]),
        ),
    ]
