# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 19:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0008_auto_20170914_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('process_id', models.BigAutoField(db_column='process_id', primary_key=True, serialize=False, verbose_name='ProcessID')),
                ('base_process_id', models.ForeignKey(blank=True, db_column='base_process_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='process.Process', verbose_name='BaseProcessID')),
            ],
            options={
                'db_table': 'process',
            },
        ),
    ]
