# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 19:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0009_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='process_type_id',
            field=models.ForeignKey(db_column='process_type_id', default=0, on_delete=django.db.models.deletion.PROTECT, to='process.ProcessType', verbose_name='ProcessTypeID'),
        ),
    ]
