# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0010_process_process_type_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='description',
            field=models.CharField(db_column='description', default='', max_length=100, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='process',
            name='run_type',
            field=models.SmallIntegerField(choices=[(-1, 'Test Run'), (0, 'Normal Run'), (1, 'ReRun All'), (2, 'ReRun Resume'), (3, 'ReRun Errors')], db_column='run_type', default=0, verbose_name='RunType'),
        ),
    ]
