# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0011_auto_20170914_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='run_status',
            field=models.SmallIntegerField(choices=[(-1, 'Pending'), (0, 'Running...'), (1, 'Finished')], db_column='run_status', default=-1, verbose_name='RunStatus'),
        ),
    ]
