# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0013_process_run_status_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='run_start_time',
            field=models.DateTimeField(blank=True, db_column='run_start_time', null=True, verbose_name='StartTime'),
        ),
    ]
