# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0015_process_run_finish_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='run_done_items',
            field=models.PositiveIntegerField(blank=True, db_column='run_done_items', null=True, verbose_name='Done'),
        ),
        migrations.AddField(
            model_name='process',
            name='run_error_items',
            field=models.PositiveIntegerField(blank=True, db_column='run_error_items', null=True, verbose_name='Errors'),
        ),
        migrations.AddField(
            model_name='process',
            name='run_total_items',
            field=models.PositiveIntegerField(blank=True, db_column='run_total_items', null=True, verbose_name='Total'),
        ),
    ]
