# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 19:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0017_auto_20170914_2052'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessJSONDataSet',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False, verbose_name='ID')),
                ('process_id', models.ForeignKey(db_column='process_id', default=0, on_delete=django.db.models.deletion.CASCADE, to='process.Process', verbose_name='ProcessID')),
            ],
            options={
                'db_table': 'process_json_data_set',
            },
        ),
    ]
