# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 19:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('json_data', '0011_auto_20170914_2025'),
        ('process', '0018_processjsondataset'),
    ]

    operations = [
        migrations.AddField(
            model_name='processjsondataset',
            name='data_set_id',
            field=models.ForeignKey(db_column='data_set_id', default=0, on_delete=django.db.models.deletion.CASCADE, to='json_data.JSONDataSet', verbose_name='DataSetID'),
        ),
        migrations.AlterUniqueTogether(
            name='processjsondataset',
            unique_together=set([('process_id', 'data_set_id')]),
        ),
    ]
