# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 19:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0019_auto_20170914_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='processjsondataset',
            name='created_timestamp',
            field=models.DateTimeField(db_column='created_timestamp', default=django.utils.timezone.now, verbose_name='Created'),
        ),
    ]
