# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 19:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0020_processjsondataset_created_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessLog',
            fields=[
                ('process_log_id', models.BigAutoField(db_column='process_log_id', primary_key=True, serialize=False, verbose_name='ProcessLogID')),
                ('process_id', models.ForeignKey(db_column='process_id', default=0, on_delete=django.db.models.deletion.CASCADE, to='process.Process', verbose_name='ProcessID')),
            ],
            options={
                'db_table': 'process_log',
            },
        ),
    ]
