# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 19:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0021_processlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='processlog',
            name='log_timestamp',
            field=models.DateTimeField(db_column='log_timestamp', default=django.utils.timezone.now, verbose_name='TimeStamp'),
        ),
    ]
