# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0022_processlog_log_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='processlog',
            name='log_entry_type',
            field=models.CharField(choices=[('DEBUG', 'Debug'), ('TRACE', 'Trace'), ('INFO', 'Informational'), ('WARN', 'Warning'), ('ERROR', 'Error'), ('FATAL', 'Fatal')], db_column='log_entry_type', default='INFO', max_length=5, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='processlog',
            name='log_message',
            field=models.TextField(db_column='log_message', default='', verbose_name='Log Message'),
        ),
    ]
