# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_code', models.CharField(db_column='country_code', max_length=2, primary_key=True, serialize=False, verbose_name='CountryCode')),
                ('description', models.CharField(db_column='description', max_length=100, unique=True, verbose_name='Description')),
            ],
            options={
                'db_table': 'refdata_country',
            },
        ),
    ]
