# Generated by Django 2.1.3 on 2018-11-20 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('currency_id', models.BigAutoField(db_column='currency_id', primary_key=True, serialize=False, verbose_name='CurrencyID')),
                ('currency_code', models.CharField(db_column='currency_code', max_length=3, unique=True, verbose_name='Ccy')),
                ('description', models.CharField(db_column='description', max_length=250, unique=True, verbose_name='Description')),
            ],
            options={
                'db_table': 'refdata_currency',
            },
        ),
    ]
