# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('currency_code', models.CharField(db_column='currency_code', max_length=3, primary_key=True, serialize=False, verbose_name='Ccy')),
                ('description', models.CharField(db_column='description', max_length=100, unique=True, verbose_name='Description')),
            ],
            options={
                'db_table': 'refdata_currency',
            },
        ),
    ]
