# Generated by Django 2.1.3 on 2018-11-20 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0002_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='base_currency_id',
            field=models.ForeignKey(blank=True, db_column='base_currency_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='reference_data.Currency', verbose_name='BaseCurrencyID'),
        ),
        migrations.AddField(
            model_name='currency',
            name='base_currency_units',
            field=models.FloatField(blank=True, db_column='base_currency_units', null=True, verbose_name='BaseCcy Units'),
        ),
    ]
