# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0002_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='base_currency_units',
            field=models.FloatField(blank=True, db_column='base_currency_units', null=True, verbose_name='BaseCcy Units'),
        ),
    ]
