# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 20:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0003_currency_base_currency_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='base_currency_code',
            field=models.ForeignKey(blank=True, db_column='base_currency_code', null=True, on_delete=django.db.models.deletion.PROTECT, to='reference_data.Currency', verbose_name='BaseCcy'),
        ),
    ]
