# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0004_currency_base_currency_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentifierType',
            fields=[
                ('identifier_type', models.CharField(db_column='identifier_type', max_length=20, primary_key=True, serialize=False, verbose_name='Identifier Type')),
                ('description', models.CharField(db_column='description', max_length=100, unique=True, verbose_name='Description')),
            ],
            options={
                'db_table': 'refdata_identifier_type',
            },
        ),
    ]
