# Generated by Django 2.1.3 on 2018-11-20 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0005_currency_base_currency_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='base_currency_units',
            field=models.FloatField(blank=True, db_column='base_currency_units', null=True, verbose_name='BaseCcy Units'),
        ),
    ]
