# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0005_identifiertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketIndex',
            fields=[
                ('market_index_id', models.AutoField(db_column='market_index_id', primary_key=True, serialize=False, verbose_name='MarketIndexID')),
                ('market_index', models.CharField(db_column='market_index', default='', max_length=100, unique=True, verbose_name='Market Index')),
                ('order_by', models.IntegerField(blank=True, db_column='order_by', null=True, verbose_name='Order By')),
            ],
            options={
                'db_table': 'refdata_market_index',
            },
        ),
    ]
