# Generated by Django 2.1.3 on 2018-11-20 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0006_currency_base_currency_units'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentifierType',
            fields=[
                ('identifier_type_id', models.BigAutoField(db_column='identifier_type_id', primary_key=True, serialize=False, verbose_name='IdentifierTypeID')),
                ('identifier_type', models.CharField(db_column='identifier_type', max_length=30, unique=True, verbose_name='IdentifierType')),
            ],
            options={
                'db_table': 'refdata_identifier_type',
            },
        ),
    ]
