# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0006_marketindex'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketindex',
            name='notes',
            field=models.CharField(blank=True, db_column='notes', max_length=250, null=True, verbose_name='Notes'),
        ),
    ]
