# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0007_marketindex_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceType',
            fields=[
                ('resource_type', models.IntegerField(db_column='resource_type', primary_key=True, serialize=False, verbose_name='ResourceType')),
                ('description', models.CharField(db_column='description', default='', max_length=100, unique=True, verbose_name='Description')),
            ],
            options={
                'db_table': 'refdata_resource_type',
            },
        ),
    ]
