# Generated by Django 2.1.3 on 2018-11-20 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0008_identifiertype_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketIndex',
            fields=[
                ('market_index_id', models.BigAutoField(db_column='market_index_id', primary_key=True, serialize=False, verbose_name='MarketIndexID')),
                ('market_index', models.CharField(db_column='market_index', default='', max_length=100, unique=True, verbose_name='Market Index')),
            ],
            options={
                'db_table': 'refdata_market_index',
            },
        ),
    ]
