# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0008_resourcetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestData',
            fields=[
                ('test_identifier', models.CharField(db_column='test_identifier', max_length=63, primary_key=True, serialize=False, verbose_name='Test Identifier')),
                ('description', models.CharField(db_column='description', max_length=100, unique=True, verbose_name='Description')),
                ('notes', models.CharField(blank=True, db_column='notes', max_length=250, null=True, verbose_name='Notes')),
            ],
            options={
                'db_table': 'refdata_test',
            },
        ),
    ]
