# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0009_testdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdata',
            name='test_boolean',
            field=models.NullBooleanField(db_column='test_boolean', verbose_name='Boolean'),
        ),
        migrations.AddField(
            model_name='testdata',
            name='test_smallint',
            field=models.SmallIntegerField(blank=True, db_column='test_smallint', null=True, verbose_name='Small Integer'),
        ),
    ]
