# Generated by Django 2.1.3 on 2018-11-20 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0009_marketindex'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketindex',
            name='description',
            field=models.CharField(blank=True, db_column='description', default='', max_length=250, verbose_name='Description'),
        ),
    ]
