# Generated by Django 2.1.3 on 2018-11-20 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0010_marketindex_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketindex',
            name='order_by',
            field=models.BigIntegerField(blank=True, db_column='order_by', null=True, verbose_name='Order By'),
        ),
    ]
