# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0010_auto_20170913_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdata',
            name='test_integer',
            field=models.IntegerField(blank=True, db_column='test_integer', null=True, verbose_name='Integer'),
        ),
    ]
