# Generated by Django 2.1.3 on 2018-11-20 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0011_marketindex_order_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceType',
            fields=[
                ('resource_type', models.BigIntegerField(db_column='resource_type', primary_key=True, serialize=False, verbose_name='ResourceType')),
                ('description', models.CharField(db_column='description', default='', max_length=250, unique=True, verbose_name='Description')),
            ],
            options={
                'db_table': 'refdata_resource_type',
            },
        ),
    ]
