# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0011_testdata_test_integer'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdata',
            name='test_bigint',
            field=models.BigIntegerField(blank=True, db_column='test_bigint', null=True, verbose_name='Big Integer'),
        ),
        migrations.AddField(
            model_name='testdata',
            name='test_float',
            field=models.FloatField(blank=True, db_column='test_float', null=True, verbose_name='Float'),
        ),
    ]
