# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0012_auto_20170913_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdata',
            name='test_decimal',
            field=models.DecimalField(blank=True, db_column='test_decimal', decimal_places=20, max_digits=40, null=True, verbose_name='Decimal'),
        ),
    ]
