# Generated by Django 2.1.3 on 2018-11-20 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0012_resourcetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestData',
            fields=[
                ('test_identifier_id', models.BigAutoField(db_column='test_identifier_id', primary_key=True, serialize=False, verbose_name='TestIdentifierID')),
            ],
            options={
                'db_table': 'refdata_test',
            },
        ),
    ]
