# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0013_testdata_test_decimal'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdata',
            name='test_date',
            field=models.DateField(blank=True, db_column='test_date', null=True, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='testdata',
            name='test_time',
            field=models.TimeField(blank=True, db_column='test_time', null=True, verbose_name='Time'),
        ),
    ]
