# Generated by Django 2.1.3 on 2018-11-20 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0014_auto_20181120_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdata',
            name='test_boolean',
            field=models.NullBooleanField(db_column='test_boolean', verbose_name='Boolean'),
        ),
        migrations.AddField(
            model_name='testdata',
            name='test_smallint',
            field=models.SmallIntegerField(blank=True, db_column='test_smallint', null=True, verbose_name='Small Integer'),
        ),
    ]
