# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0014_auto_20170913_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdata',
            name='test_datetime',
            field=models.DateTimeField(blank=True, db_column='test_datetime', null=True, verbose_name='DateTime'),
        ),
        migrations.AddField(
            model_name='testdata',
            name='test_duration',
            field=models.DurationField(blank=True, db_column='test_duration', null=True, verbose_name='Duration'),
        ),
        migrations.AddField(
            model_name='testdata',
            name='test_text',
            field=models.TextField(blank=True, db_column='test_text', null=True, verbose_name='Text'),
        ),
    ]
