# Generated by Django 2.1.3 on 2018-11-20 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0015_auto_20181120_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdata',
            name='test_integer',
            field=models.IntegerField(blank=True, db_column='test_integer', null=True, verbose_name='Integer'),
        ),
    ]
