# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0015_auto_20170913_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdata',
            name='test_inet',
            field=models.GenericIPAddressField(blank=True, db_column='test_inet', null=True, verbose_name='Generic IP Address'),
        ),
        migrations.AddField(
            model_name='testdata',
            name='test_uuid',
            field=models.UUIDField(blank=True, db_column='test_uuid', null=True, verbose_name='UUID'),
        ),
    ]
