# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 20:25
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0016_auto_20170913_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdata',
            name='test_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, db_column='test_json', null=True, verbose_name='JSON'),
        ),
    ]
