# Generated by Django 2.1.3 on 2018-11-20 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0017_auto_20181120_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdata',
            name='test_decimal',
            field=models.DecimalField(blank=True, db_column='test_decimal', decimal_places=500, max_digits=1000, null=True, verbose_name='Decimal'),
        ),
    ]
