# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0017_testdata_test_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdata',
            name='test_blob',
            field=models.BinaryField(blank=True, db_column='test_blob', null=True, verbose_name='BLOB'),
        ),
    ]
