# Generated by Django 2.1.3 on 2018-11-20 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0018_testdata_test_decimal'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdata',
            name='test_date',
            field=models.DateField(blank=True, db_column='test_date', null=True, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='testdata',
            name='test_time',
            field=models.TimeField(blank=True, db_column='test_time', null=True, verbose_name='Time'),
        ),
    ]
