# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0018_testdata_test_blob'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingExchange',
            fields=[
                ('trading_exchange', models.CharField(db_column='trading_exchange', max_length=20, primary_key=True, serialize=False, verbose_name='Trading Exchange')),
                ('description', models.CharField(db_column='description', max_length=100, unique=True, verbose_name='Description')),
            ],
            options={
                'db_table': 'refdata_trading_exchange',
            },
        ),
    ]
