# Generated by Django 2.0.5 on 2018-05-11 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0019_tradingexchange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketindex',
            name='notes',
            field=models.CharField(blank=True, db_column='notes', default='', max_length=250, verbose_name='Notes'),
        ),
    ]
