# Generated by Django 2.1.3 on 2018-11-20 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0020_auto_20181120_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdata',
            name='test_inet',
            field=models.GenericIPAddressField(blank=True, db_column='test_inet', null=True, verbose_name='Generic IP Address'),
        ),
        migrations.AddField(
            model_name='testdata',
            name='test_uuid',
            field=models.UUIDField(blank=True, db_column='test_uuid', null=True, verbose_name='UUID'),
        ),
    ]
