# Generated by Django 2.1.3 on 2018-11-20 23:24

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0021_auto_20181120_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdata',
            name='test_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, db_column='test_json', null=True, verbose_name='JSON'),
        ),
    ]
