# Generated by Django 2.1.3 on 2018-11-20 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0022_testdata_test_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdata',
            name='test_blob',
            field=models.BinaryField(blank=True, db_column='test_blob', null=True, verbose_name='BLOB'),
        ),
    ]
