# Generated by Django 2.1.3 on 2018-11-20 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0024_auto_20181120_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingexchange',
            name='description',
            field=models.CharField(db_column='description', default='', max_length=250, unique=True, verbose_name='Description'),
        ),
    ]
