# Generated by Django 2.1.3 on 2018-11-21 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0025_tradingexchange_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextTranslation',
            fields=[
                ('text_translation_id', models.BigAutoField(db_column='text_translation_id', primary_key=True, serialize=False, verbose_name='TextTranslationID')),
                ('text_context', models.CharField(db_column='text_context', max_length=100, verbose_name='TextContext')),
                ('text_lookup', models.TextField(db_column='text_lookup', verbose_name='TextLookup')),
                ('text_translation', models.TextField(blank=True, db_column='text_translation', verbose_name='TextTranslation')),
            ],
            options={
                'db_table': 'refdata_text_translation',
            },
        ),
        migrations.AlterUniqueTogether(
            name='texttranslation',
            unique_together={('text_context', 'text_lookup')},
        ),
    ]
