# Generated by Django 2.1.3 on 2018-11-22 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0026_auto_20181121_2150'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Country',
        ),
    ]
