# Generated by Django 2.1.3 on 2018-11-22 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0027_delete_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_id', models.BigAutoField(db_column='country_id', primary_key=True, serialize=False, verbose_name='CountryID')),
                ('country_code', models.CharField(db_column='country_code', max_length=2, unique=True, verbose_name='CountryCode')),
                ('description', models.CharField(db_column='description', max_length=250, unique=True, verbose_name='Description')),
            ],
            options={
                'db_table': 'refdata_country',
            },
        ),
    ]
