# Generated by Django 2.1.3 on 2018-11-22 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0028_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testdata',
            name='test_decimal',
            field=models.DecimalField(blank=True, db_column='test_decimal', decimal_places=127, max_digits=254, null=True, verbose_name='Decimal'),
        ),
    ]
