# Generated by Django 2.1.3 on 2018-11-22 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0029_auto_20181122_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testdata',
            name='test_decimal',
            field=models.DecimalField(blank=True, db_column='test_decimal', decimal_places=128, max_digits=256, null=True, verbose_name='Decimal'),
        ),
    ]
