# Generated by Django 2.1.3 on 2018-11-29 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0031_auto_20181122_2211'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResourceType',
        ),
    ]
