# Generated by Django 2.1.3 on 2018-12-21 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0032_delete_resourcetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='description',
            field=models.CharField(db_column='description', max_length=200, unique=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='description',
            field=models.CharField(db_column='description', max_length=200, unique=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='identifiertype',
            name='description',
            field=models.CharField(db_column='description', default='', max_length=200, unique=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='identifiertype',
            name='identifier_type',
            field=models.CharField(db_column='identifier_type', max_length=20, unique=True, verbose_name='IdentifierType'),
        ),
        migrations.AlterField(
            model_name='marketindex',
            name='description',
            field=models.CharField(blank=True, db_column='description', default='', max_length=200, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='testdata',
            name='description',
            field=models.CharField(db_column='description', default='', max_length=200, unique=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='tradingexchange',
            name='description',
            field=models.CharField(db_column='description', default='', max_length=200, unique=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='tradingexchange',
            name='trading_exchange',
            field=models.CharField(db_column='trading_exchange', max_length=20, unique=True, verbose_name='TradingExchange'),
        ),
    ]
