# Generated by Django 2.1.3 on 2018-12-23 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0033_auto_20181221_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='description',
            field=models.CharField(db_column='description', max_length=100, unique=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='description',
            field=models.CharField(db_column='description', max_length=100, unique=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='identifiertype',
            name='description',
            field=models.CharField(db_column='description', default='', max_length=100, unique=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='marketindex',
            name='description',
            field=models.CharField(blank=True, db_column='description', default='', max_length=100, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='testdata',
            name='description',
            field=models.CharField(db_column='description', default='', max_length=100, unique=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='tradingexchange',
            name='description',
            field=models.CharField(db_column='description', default='', max_length=100, unique=True, verbose_name='Description'),
        ),
    ]
