# Generated by Django 2.1.3 on 2018-12-23 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0034_auto_20181223_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketSector',
            fields=[
                ('market_sector_id', models.BigAutoField(db_column='market_sector_id', primary_key=True, serialize=False, verbose_name='MarketSectorID')),
                ('classification_type', models.SmallIntegerField(choices=[(0, '<None>'), (1, 'GICS'), (2, 'ICB'), (3, 'AIC'), (4, 'IA'), (5, 'Morningstar')], db_column='classification_type', default=0, verbose_name='ClassificationType')),
                ('sector_category_id', models.ForeignKey(db_column='sector_category_id', on_delete=django.db.models.deletion.PROTECT, to='reference_data.MarketSector', verbose_name='SectorCategoryID')),
            ],
            options={
                'db_table': 'refdata_market_sector',
            },
        ),
    ]
