# Generated by Django 2.1.3 on 2018-12-23 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0035_marketsector'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketsector',
            name='description',
            field=models.CharField(db_column='description', default='', max_length=100, verbose_name='Description'),
        ),
        migrations.AlterUniqueTogether(
            name='marketsector',
            unique_together={('classification_type', 'sector_category_id', 'description')},
        ),
    ]
