# Generated by Django 2.1.3 on 2019-02-08 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0037_productprovider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testdata',
            name='notes',
            field=models.CharField(blank=True, db_column='notes', max_length=250, null=True, verbose_name='Notes'),
        ),
    ]
