# Generated by Django 2.1.7 on 2019-03-14 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0038_auto_20190208_2144'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='marketsector',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='marketsector',
            name='classification_type',
        ),
        migrations.RemoveField(
            model_name='marketsector',
            name='description',
        ),
        migrations.RemoveField(
            model_name='marketsector',
            name='sector_category_id',
        ),
    ]
