# Generated by Django 2.1.7 on 2019-03-14 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0039_auto_20190314_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketsector',
            name='parent_sector_id',
            field=models.ForeignKey(db_column='parent_sector_id', default=0, on_delete=django.db.models.deletion.PROTECT, to='reference_data.MarketSector', verbose_name='ParentSectorID'),
        ),
    ]
