# Generated by Django 2.1.7 on 2019-03-14 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0040_marketsector_parent_sector_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketsector',
            name='classification_code',
            field=models.CharField(blank=True, db_column='classification_code', max_length=20, null=True, verbose_name='Classification Code'),
        ),
        migrations.AlterUniqueTogether(
            name='marketsector',
            unique_together={('parent_sector_id', 'classification_code')},
        ),
    ]
