# Generated by Django 2.1.7 on 2019-03-14 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0041_auto_20190314_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketsector',
            name='description',
            field=models.CharField(db_column='description', default='', max_length=100, verbose_name='Description'),
        ),
        migrations.AlterUniqueTogether(
            name='marketsector',
            unique_together={('parent_sector_id', 'description')},
        ),
    ]
