# Generated by Django 2.1.7 on 2019-05-07 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0042_auto_20190314_2123'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductProvider',
        ),
    ]
