# Generated by Django 2.1.7 on 2019-05-15 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0043_delete_productprovider'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentType',
            fields=[
                ('instrument_type_id', models.BigAutoField(db_column='instrument_type_id', primary_key=True, serialize=False, verbose_name='InstrumentTypeID')),
            ],
            options={
                'db_table': 'refdata_instrument_type',
            },
        ),
    ]
