# Generated by Django 2.1.7 on 2019-05-15 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0044_instrumenttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumenttype',
            name='instrument_type',
            field=models.CharField(db_column='instrument_type', default='', max_length=20, unique=True, verbose_name='InstrumentType'),
        ),
    ]
