# Generated by Django 2.1.7 on 2019-05-15 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0045_instrumenttype_instrument_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumenttype',
            name='description',
            field=models.CharField(db_column='description', default='', max_length=100, unique=True, verbose_name='Description'),
        ),
    ]
