# Generated by Django 2.1.7 on 2019-07-28 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0047_auto_20190515_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='base_currency_code',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='base_currency_units',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='description',
        ),
    ]
