# Generated by Django 2.1.7 on 2019-07-28 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0049_currency_crypto_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='description',
            field=models.CharField(blank=True, db_column='description', max_length=100, null=True, verbose_name='Description'),
        ),
    ]
