# Generated by Django 2.1.7 on 2019-07-28 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0050_currency_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='base_currency_code',
            field=models.ForeignKey(blank=True, db_column='base_currency_code', null=True, on_delete=django.db.models.deletion.PROTECT, to='reference_data.Currency', to_field='currency_code', verbose_name='BaseCcy'),
        ),
    ]
