# Generated by Django 2.1.7 on 2019-07-28 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0051_currency_base_currency_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='base_currency_units',
            field=models.FloatField(blank=True, db_column='base_currency_units', null=True, verbose_name='BaseCcy Units'),
        ),
    ]
