# Generated by Django 2.1.7 on 2019-07-28 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0053_auto_20190728_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='description',
            field=models.CharField(db_column='description', default='', max_length=100, unique=True, verbose_name='Description'),
        ),
    ]
