# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JSONDataSetType',
            fields=[
                ('data_set_type_id', models.AutoField(db_column='data_set_type_id', primary_key=True, serialize=False, verbose_name='DataSetTypeID')),
                ('data_set_type_tag', models.CharField(db_column='data_set_type_tag', default='', max_length=50, unique=True, verbose_name='DataSetTypeTag')),
                ('description', models.CharField(db_column='description', default='', max_length=100, unique=True, verbose_name='Description')),
                ('notes', models.CharField(blank=True, db_column='notes', max_length=250, null=True, verbose_name='Notes')),
            ],
            options={
                'db_table': 'json_data_set_type',
            },
        ),
    ]
