# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 19:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('json_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JSONDataSet',
            fields=[
                ('data_set_id', models.BigAutoField(db_column='data_set_id', primary_key=True, serialize=False, verbose_name='DataSetID')),
                ('description', models.CharField(blank=True, db_column='description', default='', max_length=100, null=True, verbose_name='Description')),
                ('data_set_type_id', models.ForeignKey(db_column='data_set_type_id', default=0, on_delete=django.db.models.deletion.PROTECT, to='json_data.JSONDataSetType', verbose_name='DataSetTypeID')),
            ],
            options={
                'db_table': 'json_data_set',
            },
        ),
    ]
