# Generated by Django 2.1.3 on 2019-02-10 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('json_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsondata',
            name='base_json_data_id',
            field=models.ForeignKey(blank=True, db_column='base_json_data_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='json_data.JsonData', verbose_name='BaseJsonDataID'),
        ),
        migrations.AddField(
            model_name='jsondata',
            name='data_tag',
            field=models.CharField(blank=True, db_column='data_tag', default='', max_length=50, verbose_name='DataTag'),
        ),
        migrations.AddField(
            model_name='jsondata',
            name='identifier',
            field=models.CharField(blank=True, db_column='identifier', default='', max_length=100, verbose_name='Identifier'),
        ),
        migrations.AddField(
            model_name='jsondata',
            name='resource',
            field=models.URLField(blank=True, db_column='resource', default='', max_length=2000, verbose_name='Resource'),
        ),
    ]
