# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 19:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('json_data', '0002_jsondataset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jsondataset',
            name='description',
        ),
    ]
