# Generated by Django 2.1.3 on 2019-02-11 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('json_data', '0005_auto_20190211_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsondata',
            name='description',
            field=models.CharField(blank=True, db_column='description', default='', max_length=250, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='jsondata',
            name='resource',
            field=models.URLField(blank=True, db_column='resource', default='', max_length=2000, verbose_name='Resource'),
        ),
    ]
