# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 19:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('json_data', '0005_auto_20170914_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='JSONDataItem',
            fields=[
                ('data_item_id', models.BigAutoField(db_column='data_item_id', primary_key=True, serialize=False, verbose_name='DataItemID')),
                ('error_code', models.SmallIntegerField(choices=[(0, '<None>'), (1, 'Data Source Error'), (2, 'JSON Parser Error'), (3, 'Data Integrity Error'), (4, 'Duplicate Item Identifier')], db_column='error_code', default=0, verbose_name='Error Code')),
                ('item_identifier', models.TextField(blank=True, db_column='item_identifier', null=True, verbose_name='Item Identifier')),
                ('resource_identifier', models.TextField(blank=True, db_column='resource_identifier', null=True, verbose_name='Resource Identifier')),
                ('data_set_id', models.ForeignKey(db_column='data_set_id', default=0, on_delete=django.db.models.deletion.CASCADE, to='json_data.JSONDataSet', verbose_name='DataSetID')),
            ],
            options={
                'db_table': 'json_data_item',
            },
        ),
    ]
