# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 19:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('json_data', '0006_jsondataitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jsondataitem',
            name='error_code',
        ),
        migrations.RemoveField(
            model_name='jsondataitem',
            name='item_identifier',
        ),
        migrations.RemoveField(
            model_name='jsondataitem',
            name='resource_identifier',
        ),
    ]
