# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('json_data', '0007_auto_20170914_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsondataitem',
            name='error_code',
            field=models.SmallIntegerField(choices=[(0, '<None>'), (1, 'Data Source Error'), (2, 'JSON Parser Error'), (3, 'Data Integrity Error'), (4, 'Duplicate Item Identifier')], db_column='error_code', default=0, verbose_name='Error Code'),
        ),
    ]
