# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('json_data', '0008_jsondataitem_error_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsondataitem',
            name='item_identifier',
            field=models.TextField(blank=True, db_column='item_identifier', null=True, verbose_name='Item Identifier'),
        ),
        migrations.AddField(
            model_name='jsondataitem',
            name='resource_identifier',
            field=models.TextField(blank=True, db_column='resource_identifier', null=True, verbose_name='Resource Identifier'),
        ),
    ]
