# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 19:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('json_data', '0010_jsondataitem_json_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsondataitem',
            name='created_timestamp',
            field=models.DateTimeField(db_column='created_timestamp', default=django.utils.timezone.now, verbose_name='Created'),
        ),
        migrations.AddField(
            model_name='jsondataitem',
            name='updated_timestamp',
            field=models.DateTimeField(blank=True, db_column='updated_timestamp', default=django.utils.timezone.now, null=True, verbose_name='Updated'),
        ),
    ]
