# Generated by Django 2.0.5 on 2018-05-11 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('json_data', '0011_auto_20170914_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jsondataitem',
            name='error_code',
            field=models.SmallIntegerField(choices=[(0, '<None>'), (1, 'Data Source Error'), (2, 'JSON Parser Error'), (3, 'Data Integrity Error')], db_column='error_code', default=0, verbose_name='Error Code'),
        ),
    ]
