# Generated by Django 2.0.5 on 2018-05-11 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('json_data', '0012_auto_20180511_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jsondatasettype',
            name='notes',
            field=models.CharField(blank=True, db_column='notes', default='', max_length=250, verbose_name='Notes'),
        ),
    ]
