# Generated by Django 2.0.5 on 2018-05-11 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('json_data', '0013_auto_20180511_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jsondataset',
            name='description',
            field=models.CharField(blank=True, db_column='description', default='', max_length=100, verbose_name='Description'),
        ),
    ]
