# Generated by Django 2.0.5 on 2018-05-11 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('json_data', '0014_auto_20180511_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jsondataitem',
            name='item_identifier',
            field=models.TextField(blank=True, db_column='item_identifier', default='', verbose_name='Item Identifier'),
        ),
        migrations.AlterField(
            model_name='jsondataitem',
            name='resource_identifier',
            field=models.TextField(blank=True, db_column='resource_identifier', default='', verbose_name='Resource Identifier'),
        ),
    ]
