# Generated by Django 2.0.5 on 2018-05-12 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('json_data', '0015_auto_20180511_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jsondatasettype',
            name='data_set_type_tag',
        ),
        migrations.RemoveField(
            model_name='jsondatasettype',
            name='description',
        ),
        migrations.RemoveField(
            model_name='jsondatasettype',
            name='notes',
        ),
    ]
