# Generated by Django 2.0.5 on 2018-05-12 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('json_data', '0016_auto_20180512_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsondatasettype',
            name='data_set_type',
            field=models.CharField(db_column='data_set_type', default='', max_length=50, unique=True, verbose_name='DataSetType'),
        ),
        migrations.AddField(
            model_name='jsondatasettype',
            name='description',
            field=models.CharField(db_column='description', default='', max_length=100, unique=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='jsondatasettype',
            name='notes',
            field=models.CharField(blank=True, db_column='notes', default='', max_length=250, verbose_name='Notes'),
        ),
    ]
