# Generated by Django 2.0.5 on 2018-05-23 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('json_data', '0017_auto_20180512_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='JsonData',
            fields=[
                ('json_data_id', models.BigAutoField(db_column='json_data_id', primary_key=True, serialize=False, verbose_name='JsonDataID')),
                ('error_code', models.SmallIntegerField(choices=[(0, '<None>'), (1, 'Data Source Error'), (2, 'JSON Parser Error'), (3, 'Data Integrity Error')], db_column='error_code', default=0, verbose_name='ErrorCode')),
                ('base_json_data_id', models.ForeignKey(blank=True, db_column='base_json_data_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='json_data.JsonData', verbose_name='BaseJsonDataID')),
            ],
            options={
                'db_table': 'json_data',
            },
        ),
    ]
