# Generated by Django 2.0.5 on 2018-05-23 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('json_data', '0018_jsondata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jsondata',
            name='error_code',
        ),
    ]
