# Generated by Django 2.0.5 on 2018-05-23 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('json_data', '0020_jsondata_error_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsondata',
            name='data_tag',
            field=models.CharField(blank=True, db_column='data_tag', default='', max_length=100, verbose_name='DataTag'),
        ),
        migrations.AddField(
            model_name='jsondata',
            name='identifier',
            field=models.TextField(blank=True, db_column='identifier', default='', verbose_name='Identifier'),
        ),
    ]
