# Generated by Django 2.0.5 on 2018-05-23 20:49

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('json_data', '0021_auto_20180523_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='jsondata',
            name='description',
            field=models.TextField(blank=True, db_column='description', default='', verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='jsondata',
            name='json_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, db_column='json_data', null=True, verbose_name='JSON Data'),
        ),
    ]
