# Generated by Django 2.0.5 on 2018-05-23 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('json_data', '0023_auto_20180523_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jsondataitem',
            name='data_set_id',
        ),
        migrations.DeleteModel(
            name='JSONDataItem',
        ),
    ]
