# Generated by Django 2.0.5 on 2018-05-23 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('json_data', '0024_auto_20180523_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jsondataset',
            name='data_set_type_id',
        ),
        migrations.DeleteModel(
            name='JSONDataSet',
        ),
    ]
