# Generated by Django 2.0.5 on 2018-05-23 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('json_data', '0025_auto_20180523_2155'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JSONDataSetType',
        ),
    ]
