# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('ticker_id', models.AutoField(db_column='ticker_id', primary_key=True, serialize=False, verbose_name='TickerID')),
            ],
            options={
                'db_table': 'ticker',
            },
        ),
    ]
