# Generated by Django 2.1.3 on 2018-12-23 20:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('ticker_id', models.BigAutoField(db_column='ticker_id', primary_key=True, serialize=False, verbose_name='TickerID')),
                ('ticker_uuid', models.UUIDField(db_column='ticker_uuid', default=uuid.uuid4, editable=False, unique=True, verbose_name='TickerUUID')),
            ],
            options={
                'db_table': 'ticker',
            },
        ),
    ]
