# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='status',
            field=models.SmallIntegerField(choices=[(-1, 'InActive'), (0, 'Stale'), (1, 'Active')], db_column='status', default=0, verbose_name='Status'),
        ),
    ]
