# Generated by Django 2.1.3 on 2018-12-23 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='status',
            field=models.SmallIntegerField(choices=[(-1, 'InActive'), (0, 'Stale'), (1, 'Active')], db_column='status', default=0, verbose_name='Status'),
        ),
    ]
