# Generated by Django 2.1.3 on 2018-12-23 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0002_ticker_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='description',
            field=models.CharField(db_column='description', default='', max_length=200, verbose_name='Description'),
        ),
    ]
