# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0003_ticker_identifier_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='identifier_code',
            field=models.CharField(db_column='identifier_code', default='', max_length=40, verbose_name='IdentifierCode'),
        ),
    ]
