# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0006_ticker_instrument_subtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='instrument_leverage',
            field=models.FloatField(blank=True, db_column='instrument_leverage', null=True, verbose_name='Instrument Leverage'),
        ),
        migrations.AddField(
            model_name='ticker',
            name='unit_type',
            field=models.CharField(blank=True, choices=[('Acc', 'Accumulation'), ('Inc', 'Income')], db_column='unit_type', max_length=3, null=True, verbose_name='Unit Type'),
        ),
    ]
