# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0007_auto_20170914_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='issuer_name',
            field=models.CharField(blank=True, db_column='issuer_name', max_length=100, null=True, verbose_name='Issuer Name'),
        ),
        migrations.AddField(
            model_name='ticker',
            name='security_name',
            field=models.CharField(blank=True, db_column='security_name', max_length=100, null=True, verbose_name='Security Name'),
        ),
    ]
