# Generated by Django 2.1.3 on 2018-12-23 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0008_ticker_unit_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticker',
            name='instrument_subtype',
        ),
        migrations.RemoveField(
            model_name='ticker',
            name='instrument_type',
        ),
        migrations.RemoveField(
            model_name='ticker',
            name='product_leverage',
        ),
        migrations.RemoveField(
            model_name='ticker',
            name='product_provider_id',
        ),
        migrations.RemoveField(
            model_name='ticker',
            name='unit_type',
        ),
    ]
