# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 20:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0019_tradingexchange'),
        ('ticker', '0008_auto_20170914_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='registered_country_code',
            field=models.ForeignKey(blank=True, db_column='registered_country_code', null=True, on_delete=django.db.models.deletion.PROTECT, to='reference_data.Country', verbose_name='Registered Country'),
        ),
    ]
