# Generated by Django 2.1.3 on 2018-12-23 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0009_auto_20181223_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='issuer_name',
            field=models.CharField(blank=True, db_column='issuer_name', default='', max_length=100, verbose_name='Issuer Name'),
        ),
        migrations.AddField(
            model_name='ticker',
            name='security_name',
            field=models.CharField(blank=True, db_column='security_name', default='', max_length=100, verbose_name='Security Name'),
        ),
    ]
