# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 20:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0019_tradingexchange'),
        ('ticker', '0009_ticker_registered_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='issue_size',
            field=models.FloatField(blank=True, db_column='issue_size', null=True, verbose_name='Issue Size'),
        ),
        migrations.AddField(
            model_name='ticker',
            name='quote_units',
            field=models.FloatField(blank=True, db_column='quote_units', null=True, verbose_name='Quote Units'),
        ),
        migrations.AddField(
            model_name='ticker',
            name='trading_currency',
            field=models.ForeignKey(blank=True, db_column='trading_currency', null=True, on_delete=django.db.models.deletion.PROTECT, to='reference_data.Currency', verbose_name='Trading Currency'),
        ),
        migrations.AddField(
            model_name='ticker',
            name='trading_exchange',
            field=models.ForeignKey(blank=True, db_column='trading_exchange', null=True, on_delete=django.db.models.deletion.PROTECT, to='reference_data.TradingExchange', verbose_name='Trading Exchange'),
        ),
    ]
