# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0010_auto_20170914_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='listing_type',
            field=models.CharField(blank=True, db_column='listing_type', max_length=20, null=True, verbose_name='Listing Type'),
        ),
    ]
