# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0011_ticker_listing_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='listing_date',
            field=models.DateField(blank=True, db_column='listing_date', null=True, verbose_name='Listing Date'),
        ),
    ]
