# Generated by Django 2.1.3 on 2018-12-23 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0037_productprovider'),
        ('ticker', '0011_ticker_instrument_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='instrument_subtype',
            field=models.CharField(blank=True, db_column='instrument_subtype', default='', max_length=30, verbose_name='Instrument Subtype'),
        ),
        migrations.AddField(
            model_name='ticker',
            name='product_provider_id',
            field=models.ForeignKey(blank=True, db_column='product_provider_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='reference_data.ProductProvider', verbose_name='Product Provider'),
        ),
    ]
