# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0012_ticker_listing_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='listing_category',
            field=models.CharField(blank=True, db_column='listing_category', max_length=60, null=True, verbose_name='Listing Category'),
        ),
    ]
