# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0013_ticker_listing_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='exchange_market_size',
            field=models.FloatField(blank=True, db_column='exchange_market_size', null=True, verbose_name='Exchange Market Size'),
        ),
        migrations.AddField(
            model_name='ticker',
            name='trading_service',
            field=models.CharField(blank=True, db_column='trading_service', max_length=60, null=True, verbose_name='Trading Service'),
        ),
    ]
