# Generated by Django 2.1.3 on 2018-12-23 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0037_productprovider'),
        ('ticker', '0014_ticker_unit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='registered_country_id',
            field=models.ForeignKey(blank=True, db_column='registered_country_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='reference_data.Country', verbose_name='Registered Country'),
        ),
    ]
