# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0014_auto_20170914_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='market_segment_code',
            field=models.CharField(blank=True, db_column='market_segment_code', max_length=20, null=True, verbose_name='Market Segment Code'),
        ),
    ]
