# Generated by Django 2.1.3 on 2018-12-23 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0015_ticker_registered_country_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='issue_size',
            field=models.FloatField(blank=True, db_column='issue_size', null=True, verbose_name='Issue Size'),
        ),
        migrations.AddField(
            model_name='ticker',
            name='quote_units',
            field=models.FloatField(blank=True, db_column='quote_units', null=True, verbose_name='Quote Units'),
        ),
    ]
