# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0015_ticker_market_segment_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='market_sector',
            field=models.CharField(blank=True, db_column='market_sector', max_length=60, null=True, verbose_name='Market Sector'),
        ),
        migrations.AddField(
            model_name='ticker',
            name='market_subsector',
            field=models.CharField(blank=True, db_column='market_subsector', max_length=60, null=True, verbose_name='Market Subsector'),
        ),
        migrations.AddField(
            model_name='ticker',
            name='morningstar_category',
            field=models.CharField(blank=True, db_column='morningstar_category', max_length=100, null=True, verbose_name='Morningstar Category'),
        ),
    ]
