# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0016_auto_20170914_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='issue_date',
            field=models.DateField(blank=True, db_column='issue_date', null=True, verbose_name='Issue Date'),
        ),
        migrations.AddField(
            model_name='ticker',
            name='maturity_date',
            field=models.DateField(blank=True, db_column='maturity_date', null=True, verbose_name='Maturity Date'),
        ),
    ]
