# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0017_auto_20170914_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='coupon_type',
            field=models.CharField(blank=True, db_column='coupon_type', max_length=20, null=True, verbose_name='Coupon Type'),
        ),
        migrations.AddField(
            model_name='ticker',
            name='coupon_value',
            field=models.FloatField(blank=True, db_column='coupon_value', null=True, verbose_name='Coupon Value'),
        ),
    ]
