# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0019_tradingexchange'),
        ('ticker', '0018_auto_20170914_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='coupon_period',
            field=models.CharField(blank=True, db_column='coupon_period', max_length=20, null=True, verbose_name='Coupon Period'),
        ),
        migrations.AlterUniqueTogether(
            name='ticker',
            unique_together=set([('identifier_type', 'identifier_code')]),
        ),
    ]
