# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 20:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0019_auto_20170914_2115'),
    ]

    operations = [
        migrations.CreateModel(
            name='TickerIdentifier',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker_id', models.ForeignKey(db_column='ticker_id', default=0, on_delete=django.db.models.deletion.CASCADE, to='ticker.Ticker', verbose_name='TickerID')),
            ],
            options={
                'db_table': 'ticker_identifier',
            },
        ),
    ]
