# Generated by Django 2.1.3 on 2018-12-23 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0021_ticker_listing_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='listing_date',
            field=models.DateField(blank=True, db_column='listing_date', null=True, verbose_name='Listing Date'),
        ),
    ]
