# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0021_auto_20170914_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickeridentifier',
            name='identifier_code',
            field=models.CharField(db_column='identifier_code', default='', max_length=40, verbose_name='Identifier Code'),
        ),
    ]
