# Generated by Django 2.1.3 on 2018-12-23 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0022_ticker_listing_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='exchange_market_size',
            field=models.FloatField(blank=True, db_column='exchange_market_size', null=True, verbose_name='Exchange Market Size'),
        ),
        migrations.AddField(
            model_name='ticker',
            name='trading_service',
            field=models.CharField(blank=True, db_column='trading_service', default='', max_length=60, verbose_name='Trading Service'),
        ),
    ]
