# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 20:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0019_tradingexchange'),
        ('ticker', '0023_tickermarketindex'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickermarketindex',
            name='market_index_id',
            field=models.ForeignKey(db_column='market_index_id', default=0, on_delete=django.db.models.deletion.PROTECT, to='reference_data.MarketIndex', verbose_name='MarketIndexID'),
        ),
        migrations.AlterUniqueTogether(
            name='tickermarketindex',
            unique_together=set([('ticker_id', 'market_index_id')]),
        ),
    ]
