# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 20:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0019_tradingexchange'),
        ('ticker', '0025_tickerresource'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickerresource',
            name='resource_type',
            field=models.ForeignKey(db_column='resource_type', default=0, on_delete=django.db.models.deletion.PROTECT, to='reference_data.ResourceType', verbose_name='ResourceType'),
        ),
        migrations.AddField(
            model_name='tickerresource',
            name='resource_url',
            field=models.URLField(db_column='resource_url', default='', max_length=16000, verbose_name='ResourceURL'),
        ),
        migrations.AlterUniqueTogether(
            name='tickerresource',
            unique_together=set([('ticker_id', 'resource_type')]),
        ),
    ]
