# Generated by Django 2.1.3 on 2018-12-24 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0037_productprovider'),
        ('ticker', '0025_ticker_market_sector_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='morningstar_category_id',
            field=models.ForeignKey(blank=True, db_column='morningstar_category_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='morningstar_category', to='reference_data.MarketSector', verbose_name='Morningstar Category'),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='market_sector_id',
            field=models.ForeignKey(blank=True, db_column='market_sector_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='market_sector', to='reference_data.MarketSector', verbose_name='Market Sector'),
        ),
    ]
