# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 20:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0019_tradingexchange'),
        ('ticker', '0027_tickereoddata'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickereoddata',
            name='close_date',
            field=models.DateField(db_column='close_date', default=datetime.date.today, verbose_name='Close Date'),
        ),
        migrations.AddField(
            model_name='tickereoddata',
            name='data_source',
            field=models.ForeignKey(db_column='data_source', default=0, on_delete=django.db.models.deletion.PROTECT, to='reference_data.ResourceType', verbose_name='DataSource'),
        ),
        migrations.AddField(
            model_name='tickereoddata',
            name='open_value',
            field=models.FloatField(blank=True, db_column='open_value', null=True, verbose_name='Open'),
        ),
        migrations.AlterUniqueTogether(
            name='tickereoddata',
            unique_together=set([('ticker_id', 'close_date')]),
        ),
    ]
