# Generated by Django 2.1.3 on 2018-12-24 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0027_ticker_json_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticker',
            name='exchange_market_size',
        ),
        migrations.RemoveField(
            model_name='ticker',
            name='instrument_subtype',
        ),
        migrations.RemoveField(
            model_name='ticker',
            name='instrument_type',
        ),
        migrations.RemoveField(
            model_name='ticker',
            name='issue_size',
        ),
        migrations.RemoveField(
            model_name='ticker',
            name='json_data',
        ),
        migrations.RemoveField(
            model_name='ticker',
            name='listing_category',
        ),
        migrations.RemoveField(
            model_name='ticker',
            name='listing_code',
        ),
        migrations.RemoveField(
            model_name='ticker',
            name='listing_date',
        ),
        migrations.RemoveField(
            model_name='ticker',
            name='listing_type',
        ),
        migrations.RemoveField(
            model_name='ticker',
            name='market_sector_id',
        ),
        migrations.RemoveField(
            model_name='ticker',
            name='morningstar_category_id',
        ),
        migrations.RemoveField(
            model_name='ticker',
            name='product_leverage',
        ),
        migrations.RemoveField(
            model_name='ticker',
            name='product_provider_id',
        ),
        migrations.RemoveField(
            model_name='ticker',
            name='quote_units',
        ),
        migrations.RemoveField(
            model_name='ticker',
            name='registered_country_id',
        ),
        migrations.RemoveField(
            model_name='ticker',
            name='trading_currency_id',
        ),
        migrations.RemoveField(
            model_name='ticker',
            name='trading_exchange_id',
        ),
        migrations.RemoveField(
            model_name='ticker',
            name='trading_segment',
        ),
        migrations.RemoveField(
            model_name='ticker',
            name='trading_service',
        ),
        migrations.RemoveField(
            model_name='ticker',
            name='unit_type',
        ),
    ]
