# Generated by Django 2.1.3 on 2018-12-24 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0028_auto_20181224_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='instrument_model',
            field=models.SmallIntegerField(choices=[(0, '<None>'), (1, 'Commodity'), (2, 'FX'), (3, 'Index'), (4, 'Bond'), (5, 'Share'), (6, 'InvestmentTrust'), (7, 'ETP'), (8, 'Fund')], db_column='instrument_model', default=0, verbose_name='Instrument Model'),
        ),
    ]
