# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0030_auto_20170914_2125'),
    ]

    operations = [
        migrations.CreateModel(
            name='TickerEodDataAuditRecord',
            fields=[
                ('audit_id', models.BigAutoField(db_column='audit_id', primary_key=True, serialize=False, verbose_name='AuditID')),
            ],
            options={
                'db_table': 'ticker_eod_data_audit_record',
            },
        ),
    ]
