# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 20:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0031_tickereoddataauditrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickereoddataauditrecord',
            name='audit_action',
            field=models.CharField(choices=[('-', 'None'), ('I', 'Insert'), ('U', 'Update'), ('D', 'Delete')], db_column='audit_action', default='-', max_length=1, verbose_name='Audit Action'),
        ),
        migrations.AddField(
            model_name='tickereoddataauditrecord',
            name='audit_timestamp',
            field=models.DateTimeField(db_column='audit_timestamp', default=django.utils.timezone.now, verbose_name='Audit Timestamp'),
        ),
        migrations.AddField(
            model_name='tickereoddataauditrecord',
            name='ticker_eod_data_id',
            field=models.BigIntegerField(db_column='ticker_eod_data_id', default=0, verbose_name='TickerEodDataID'),
        ),
        migrations.AddField(
            model_name='tickereoddataauditrecord',
            name='ticker_id',
            field=models.ForeignKey(db_column='ticker_id', default=0, on_delete=django.db.models.deletion.CASCADE, to='ticker.Ticker', verbose_name='TickerID'),
        ),
    ]
