# Generated by Django 2.1.3 on 2018-12-24 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0032_ticker_product_leverage'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='unit_type',
            field=models.CharField(blank=True, choices=[('Acc', 'Accumulation'), ('Inc', 'Income')], db_column='unit_type', default='', max_length=3, verbose_name='Unit Type'),
        ),
    ]
