# Generated by Django 2.1.3 on 2018-12-24 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0034_ticker_registered_country_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='issue_size',
            field=models.FloatField(blank=True, db_column='issue_size', null=True, verbose_name='Issue Size'),
        ),
    ]
