# Generated by Django 2.0.5 on 2018-05-11 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0035_auto_20170914_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticker',
            name='instrument_subtype',
            field=models.CharField(blank=True, db_column='instrument_subtype', default='', max_length=30, verbose_name='Instrument Subtype'),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='instrument_type',
            field=models.CharField(blank=True, db_column='instrument_type', default='', max_length=30, verbose_name='Instrument Type'),
        ),
    ]
