# Generated by Django 2.1.3 on 2018-12-24 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0037_productprovider'),
        ('ticker', '0036_ticker_quote_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='quote_currency_id',
            field=models.ForeignKey(blank=True, db_column='quote_currency_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quote_currency', to='reference_data.Currency', verbose_name='Quote Currency'),
        ),
    ]
