# Generated by Django 2.0.5 on 2018-05-11 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0037_auto_20180511_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticker',
            name='coupon_period',
            field=models.CharField(blank=True, db_column='coupon_period', default='', max_length=20, verbose_name='Coupon Period'),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='coupon_type',
            field=models.CharField(blank=True, db_column='coupon_type', default='', max_length=20, verbose_name='Coupon Type'),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='issuer_name',
            field=models.CharField(blank=True, db_column='issuer_name', default='', max_length=100, verbose_name='Issuer Name'),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='listing_category',
            field=models.CharField(blank=True, db_column='listing_category', default='', max_length=60, verbose_name='Listing Category'),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='listing_type',
            field=models.CharField(blank=True, db_column='listing_type', default='', max_length=20, verbose_name='Listing Type'),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='market_sector',
            field=models.CharField(blank=True, db_column='market_sector', default='', max_length=60, verbose_name='Market Sector'),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='market_segment_code',
            field=models.CharField(blank=True, db_column='market_segment_code', default='', max_length=20, verbose_name='Market Segment Code'),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='market_subsector',
            field=models.CharField(blank=True, db_column='market_subsector', default='', max_length=60, verbose_name='Market Subsector'),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='morningstar_category',
            field=models.CharField(blank=True, db_column='morningstar_category', default='', max_length=100, verbose_name='Morningstar Category'),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='security_name',
            field=models.CharField(blank=True, db_column='security_name', default='', max_length=100, verbose_name='Security Name'),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='trading_service',
            field=models.CharField(blank=True, db_column='trading_service', default='', max_length=60, verbose_name='Trading Service'),
        ),
    ]
