# Generated by Django 2.1.3 on 2018-12-24 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0037_productprovider'),
        ('ticker', '0037_ticker_quote_currency_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='trading_currency_id',
            field=models.ForeignKey(blank=True, db_column='trading_currency_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trading_currency', to='reference_data.Currency', verbose_name='Trading Currency'),
        ),
    ]
