# Generated by Django 2.0.5 on 2018-05-19 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0038_auto_20180511_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickereoddataauditrecord',
            name='audit_action',
            field=models.SmallIntegerField(choices=[('1', 'Insert'), ('0', 'Update'), ('-1', 'Delete')], db_column='audit_action', default='0', verbose_name='Audit Action'),
        ),
    ]
