# Generated by Django 2.1.3 on 2018-12-24 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0043_auto_20181224_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='trading_segment',
            field=models.CharField(blank=True, db_column='trading_segment', default='', max_length=20, verbose_name='Trading Segment'),
        ),
    ]
