# Generated by Django 2.1.3 on 2018-12-24 20:44

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0046_ticker_morningstar_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='json_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, db_column='json_data', null=True, verbose_name='JSON Data'),
        ),
    ]
