# Generated by Django 2.1.3 on 2018-12-24 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0037_productprovider'),
        ('ticker', '0049_tickeridentifier_identifier_type_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickeridentifier',
            name='identifier_code',
            field=models.CharField(db_column='identifier_code', default='', max_length=40, verbose_name='Identifier Code'),
        ),
        migrations.AlterUniqueTogether(
            name='tickeridentifier',
            unique_together={('ticker_id', 'identifier_type_id')},
        ),
    ]
