# Generated by Django 2.1.3 on 2018-12-24 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0037_productprovider'),
        ('ticker', '0051_tickermarketindex'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickermarketindex',
            name='market_index_id',
            field=models.ForeignKey(db_column='market_index_id', default=0, on_delete=django.db.models.deletion.PROTECT, to='reference_data.MarketIndex', verbose_name='MarketIndexID'),
        ),
        migrations.AlterUniqueTogether(
            name='tickermarketindex',
            unique_together={('ticker_id', 'market_index_id')},
        ),
    ]
