# Generated by Django 2.1.3 on 2019-02-09 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0055_tickerresource_resource_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickerresource',
            name='resource_url',
            field=models.URLField(db_column='resource', default='', max_length=2000, verbose_name='Resource'),
        ),
    ]
