# Generated by Django 2.1.3 on 2019-02-09 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0057_tickereoddata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TickerEodData',
        ),
    ]
