# Generated by Django 2.1.3 on 2019-02-09 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0059_tickereoddata'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickereoddata',
            name='ticker_id',
            field=models.ForeignKey(db_column='ticker_id', default=0, on_delete=django.db.models.deletion.CASCADE, to='ticker.Ticker', verbose_name='TickerID'),
        ),
    ]
