# Generated by Django 2.1.3 on 2019-02-09 22:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0060_tickereoddata_ticker_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickereoddata',
            name='close_date',
            field=models.DateField(db_column='close_date', default=datetime.date.today, verbose_name='Close Date'),
        ),
        migrations.AlterUniqueTogether(
            name='tickereoddata',
            unique_together={('ticker_id', 'close_date')},
        ),
    ]
