# Generated by Django 2.1.3 on 2019-02-09 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0062_tickereoddata_data_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickereoddata',
            name='open_value',
            field=models.FloatField(blank=True, db_column='open_value', null=True, verbose_name='Open'),
        ),
    ]
