# Generated by Django 2.1.3 on 2019-02-09 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0063_tickereoddata_open_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickereoddata',
            name='high_value',
            field=models.FloatField(blank=True, db_column='high_value', null=True, verbose_name='High'),
        ),
        migrations.AddField(
            model_name='tickereoddata',
            name='low_value',
            field=models.FloatField(blank=True, db_column='low_value', null=True, verbose_name='Low'),
        ),
    ]
