# Generated by Django 2.1.3 on 2019-02-09 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0064_auto_20190209_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickereoddata',
            name='close_value',
            field=models.FloatField(blank=True, db_column='close_value', null=True, verbose_name='Close'),
        ),
        migrations.AddField(
            model_name='tickereoddata',
            name='volume',
            field=models.FloatField(blank=True, db_column='volume', null=True, verbose_name='Volume'),
        ),
    ]
