# Generated by Django 2.1.3 on 2019-02-09 22:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0066_tickereoddata_created_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickereoddata',
            name='updated_timestamp',
            field=models.DateTimeField(blank=True, db_column='updated_timestamp', default=django.utils.timezone.now, null=True, verbose_name='Updated'),
        ),
    ]
