# Generated by Django 2.1.3 on 2019-02-12 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0067_tickereoddata_updated_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickereoddata',
            name='ticker_id',
            field=models.ForeignKey(db_column='ticker_id', default=0, on_delete=django.db.models.deletion.PROTECT, to='ticker.Ticker', verbose_name='TickerID'),
        ),
        migrations.AlterField(
            model_name='tickeridentifier',
            name='ticker_id',
            field=models.ForeignKey(db_column='ticker_id', default=0, on_delete=django.db.models.deletion.PROTECT, to='ticker.Ticker', verbose_name='TickerID'),
        ),
        migrations.AlterField(
            model_name='tickermarketindex',
            name='ticker_id',
            field=models.ForeignKey(db_column='ticker_id', default=0, on_delete=django.db.models.deletion.PROTECT, to='ticker.Ticker', verbose_name='TickerID'),
        ),
        migrations.AlterField(
            model_name='tickerresource',
            name='ticker_id',
            field=models.ForeignKey(db_column='ticker_id', default=0, on_delete=django.db.models.deletion.PROTECT, to='ticker.Ticker', verbose_name='TickerID'),
        ),
    ]
