# Generated by Django 2.1.3 on 2019-02-12 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0068_auto_20190212_2122'),
    ]

    operations = [
        migrations.CreateModel(
            name='TickerUpdateProcess',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker_id', models.ForeignKey(db_column='ticker_id', default=0, on_delete=django.db.models.deletion.PROTECT, to='ticker.Ticker', verbose_name='TickerID')),
            ],
            options={
                'db_table': 'ticker_update_process',
            },
        ),
    ]
