# Generated by Django 2.1.3 on 2019-02-12 21:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0070_auto_20190212_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickerupdateprocess',
            name='last_checked',
            field=models.DateTimeField(db_column='last_checked', default=django.utils.timezone.now, verbose_name='Last Checked'),
        ),
    ]
