# Generated by Django 2.1.3 on 2019-02-13 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0072_auto_20190213_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickerbatchprocesstype',
            name='ticker_id',
            field=models.ForeignKey(db_column='ticker_id', default=0, on_delete=django.db.models.deletion.PROTECT, to='ticker.Ticker', verbose_name='TickerID'),
        ),
    ]
