# Generated by Django 2.1.7 on 2019-02-21 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0075_tickerbatchprocesstype_last_checked'),
    ]

    operations = [
        migrations.CreateModel(
            name='TickerBatchProcess',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker_id', models.ForeignKey(db_column='ticker_id', default=0, on_delete=django.db.models.deletion.PROTECT, to='ticker.Ticker', verbose_name='TickerID')),
            ],
            options={
                'db_table': 'ticker_batch_process',
            },
        ),
        migrations.AlterUniqueTogether(
            name='tickerbatchprocesstype',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='tickerbatchprocesstype',
            name='batch_process_type_id',
        ),
        migrations.RemoveField(
            model_name='tickerbatchprocesstype',
            name='ticker_id',
        ),
        migrations.DeleteModel(
            name='TickerBatchProcessType',
        ),
    ]
