# Generated by Django 2.1.7 on 2019-02-21 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('batch_process', '0037_batchprocesstaskintervention_intervention_timestamp'),
        ('ticker', '0077_tickerbatchprocess_batch_process_type_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickerbatchprocess',
            name='batch_process_id',
            field=models.ForeignKey(db_column='batch_process_id', default=0, on_delete=django.db.models.deletion.PROTECT, to='batch_process.BatchProcess', verbose_name='BatchProcessID'),
        ),
        migrations.AlterUniqueTogether(
            name='tickerbatchprocess',
            unique_together={('ticker_id', 'batch_process_type_id')},
        ),
    ]
