# Generated by Django 2.1.7 on 2019-02-21 21:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0078_auto_20190221_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickerbatchprocess',
            name='last_checked',
            field=models.DateTimeField(db_column='last_checked', default=django.utils.timezone.now, verbose_name='Last Checked'),
        ),
    ]
