# Generated by Django 2.1.7 on 2019-03-17 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0080_auto_20190317_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickereoddata',
            name='open_level',
            field=models.FloatField(blank=True, db_column='open_level', null=True, verbose_name='Open'),
        ),
    ]
