# Generated by Django 2.1.7 on 2019-03-17 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0082_auto_20190317_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickereoddata',
            name='close_level',
            field=models.FloatField(blank=True, db_column='close_level', null=True, verbose_name='Close'),
        ),
        migrations.AddField(
            model_name='tickereoddata',
            name='volume',
            field=models.FloatField(blank=True, db_column='volume', null=True, verbose_name='Volume'),
        ),
    ]
