# Generated by Django 2.1.7 on 2019-03-17 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0087_auto_20190317_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickereoddata',
            name='close_value',
            field=models.FloatField(blank=True, db_column='close_value', null=True, verbose_name='Close'),
        ),
        migrations.AddField(
            model_name='tickereoddata',
            name='volume',
            field=models.FloatField(blank=True, db_column='volume', null=True, verbose_name='Volume'),
        ),
    ]
