# Generated by Django 2.1.7 on 2019-05-07 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0089_auto_20190317_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticker',
            name='product_provider_id',
        ),
    ]
