# Generated by Django 2.1.7 on 2019-05-11 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0090_remove_ticker_product_provider_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticker',
            name='instrument_model',
        ),
        migrations.AlterField(
            model_name='ticker',
            name='instrument_type',
            field=models.CharField(blank=True, choices=[('COMMODITY', 'Commodity'), ('FX', 'Foreign Exchange'), ('INDEX', 'Index'), ('BOND', 'Bond'), ('EQUITY', 'Company Share'), ('IT', 'Investment Trust'), ('ETP', 'Exchange-Traded Product'), ('FUND', 'Fund')], db_column='instrument_type', default='', max_length=30, verbose_name='Instrument Type'),
        ),
    ]
