# Generated by Django 2.1.7 on 2019-05-14 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0093_auto_20190514_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='instrument_type',
            field=models.CharField(blank=True, choices=[('COMMODITY', 'Commodity'), ('DEBT', 'Debt'), ('EQUITY', 'Company Share'), ('ETP', 'Exchange-Traded Product'), ('FUND', 'Fund'), ('FX', 'Foreign Exchange'), ('INDEX', 'Index'), ('IT', 'Investment Trust')], db_column='instrument_type', default='', max_length=30, verbose_name='Instrument Type'),
        ),
    ]
