# Generated by Django 2.1.7 on 2019-05-14 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0095_auto_20190514_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='security_name',
            field=models.CharField(blank=True, db_column='security_name', default='', max_length=100, verbose_name='Security Name'),
        ),
        migrations.AddField(
            model_name='ticker',
            name='security_type',
            field=models.CharField(blank=True, db_column='security_type', default='', max_length=30, verbose_name='Security Type'),
        ),
    ]
