# Generated by Django 2.1.7 on 2019-05-14 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0096_auto_20190514_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='product_leverage',
            field=models.FloatField(blank=True, db_column='product_leverage', null=True, verbose_name='Product Leverage'),
        ),
        migrations.AddField(
            model_name='ticker',
            name='unit_type',
            field=models.CharField(blank=True, choices=[('Acc', 'Accumulation'), ('Inc', 'Income')], db_column='unit_type', default='', max_length=3, verbose_name='Unit Type'),
        ),
    ]
