# Generated by Django 2.1.7 on 2019-05-15 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0047_auto_20190515_2121'),
        ('ticker', '0108_auto_20190515_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='instrument_type_id',
            field=models.ForeignKey(blank=True, db_column='instrument_type_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='reference_data.InstrumentType', verbose_name='Instrument Type'),
        ),
    ]
