# Generated by Django 2.1.7 on 2019-05-15 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference_data', '0047_auto_20190515_2121'),
        ('ticker', '0111_auto_20190515_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='registered_country_id',
            field=models.ForeignKey(blank=True, db_column='registered_country_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='reference_data.Country', verbose_name='Registered Country'),
        ),
    ]
