# Generated by Django 2.1.7 on 2019-05-16 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0125_auto_20190516_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticker',
            name='issuer_name',
        ),
        migrations.RemoveField(
            model_name='ticker',
            name='issuer_type',
        ),
    ]
