# Generated by Django 2.1.7 on 2019-05-16 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0133_auto_20190516_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='listing_type',
            field=models.CharField(blank=True, db_column='listing_type', default='', max_length=20, verbose_name='Listing Type'),
        ),
    ]
