# Generated by Django 2.1.7 on 2019-05-16 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0136_auto_20190516_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='exchange_market_size',
            field=models.FloatField(blank=True, db_column='exchange_market_size', null=True, verbose_name='Exchange Market Size'),
        ),
        migrations.AddField(
            model_name='ticker',
            name='trading_service',
            field=models.CharField(blank=True, db_column='trading_service', default='', max_length=60, verbose_name='Trading Service'),
        ),
    ]
