# Generated by Django 2.1.7 on 2019-05-16 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0137_auto_20190516_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticker',
            name='trading_segment',
            field=models.CharField(blank=True, db_column='trading_segment', default='', max_length=20, verbose_name='Trading Segment'),
        ),
    ]
