# Generated by Django 3.1 on 2020-09-15 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0140_ticker_json_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticker',
            name='json_data',
            field=models.JSONField(blank=True, db_column='json_data', null=True, verbose_name='JSON Data'),
        ),
    ]
