# Generated by Django 3.2.4 on 2021-08-11 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0141_auto_20200915_2318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticker',
            name='exchange_market_size',
        ),
        migrations.RemoveField(
            model_name='ticker',
            name='listing_category',
        ),
        migrations.RemoveField(
            model_name='ticker',
            name='listing_code',
        ),
        migrations.RemoveField(
            model_name='ticker',
            name='trading_segment',
        ),
        migrations.RemoveField(
            model_name='ticker',
            name='trading_service',
        ),
    ]
