# Generated by Django 2.0.5 on 2018-05-21 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BatchType',
            fields=[
                ('batch_type_id', models.AutoField(db_column='batch_type_id', primary_key=True, serialize=False, verbose_name='BatchTypeID')),
                ('description', models.CharField(db_column='description', default='', max_length=100, unique=True, verbose_name='Description')),
                ('notes', models.CharField(blank=True, db_column='notes', default='', max_length=250, verbose_name='Notes')),
            ],
            options={
                'db_table': 'batch_type',
            },
        ),
    ]
