# Generated by Django 2.1.3 on 2019-02-10 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BatchProcessType',
            fields=[
                ('batch_process_type_id', models.AutoField(db_column='batch_process_type_id', primary_key=True, serialize=False, verbose_name='BatchProcessTypeID')),
            ],
            options={
                'db_table': 'batch_process_type',
            },
        ),
    ]
