# Generated by Django 2.1.3 on 2019-02-10 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch_process', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchprocesstype',
            name='batch_process_type_tag',
            field=models.CharField(db_column='batch_process_type_tag', default='', max_length=50, unique=True, verbose_name='BatchProcessTypeTag'),
        ),
        migrations.AddField(
            model_name='batchprocesstype',
            name='description',
            field=models.CharField(db_column='description', default='', max_length=100, unique=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='batchprocesstype',
            name='notes',
            field=models.CharField(blank=True, db_column='notes', default='', max_length=250, verbose_name='Notes'),
        ),
    ]
