# Generated by Django 2.0.5 on 2018-05-25 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch_process', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchProcessType',
            fields=[
                ('batch_process_type_id', models.AutoField(db_column='batch_process_type_id', primary_key=True, serialize=False, verbose_name='BatchProcessTypeID')),
                ('batch_process_type_tag', models.CharField(db_column='batch_process_type_tag', default='', max_length=100, unique=True, verbose_name='BatchProcessTypeTag')),
                ('description', models.CharField(db_column='description', default='', max_length=100, unique=True, verbose_name='Description')),
                ('notes', models.CharField(blank=True, db_column='notes', default='', max_length=250, verbose_name='Notes')),
            ],
            options={
                'db_table': 'batch_process_type',
            },
        ),
    ]
