# Generated by Django 2.0.5 on 2018-05-25 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch_process', '0002_batchprocesstype'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchprocesstype',
            name='execution_handler',
            field=models.CharField(db_column='execution_handler', default='', max_length=100, verbose_name='ExecutionHandler'),
        ),
    ]
