# Generated by Django 2.0.5 on 2018-05-25 20:48

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batch_process', '0003_batchprocesstype_execution_handler'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchprocesstype',
            name='configuration',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, db_column='configuration', null=True, verbose_name='Configuration'),
        ),
    ]
