# Generated by Django 2.0.5 on 2018-05-25 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('batch_process', '0004_batchprocesstype_configuration'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchTypeBatchProcessType',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_type_id', models.ForeignKey(db_column='batch_type_id', default=0, on_delete=django.db.models.deletion.CASCADE, to='batch_process.BatchType', verbose_name='BatchTypeID')),
            ],
            options={
                'db_table': 'batch_type_batch_process_type',
            },
        ),
    ]
