# Generated by Django 2.1.3 on 2019-02-10 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch_process', '0004_batchprocesstype_configuration'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchProcess',
            fields=[
                ('batch_process_id', models.BigAutoField(db_column='batch_process_id', primary_key=True, serialize=False, verbose_name='BatchProcessID')),
            ],
            options={
                'db_table': 'batch_process',
            },
        ),
    ]
