# Generated by Django 2.1.3 on 2019-02-10 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('batch_process', '0005_batchprocess'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchprocess',
            name='batch_process_type_id',
            field=models.ForeignKey(db_column='batch_process_type_id', default=0, on_delete=django.db.models.deletion.PROTECT, to='batch_process.BatchProcessType', verbose_name='BatchProcessTypeID'),
        ),
    ]
