# Generated by Django 2.0.5 on 2018-05-25 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('batch_process', '0005_batchtypebatchprocesstype'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchtypebatchprocesstype',
            name='batch_process_type_id',
            field=models.ForeignKey(db_column='batch_process_type_id', default=0, on_delete=django.db.models.deletion.CASCADE, to='batch_process.BatchProcessType', verbose_name='BatchProcessTypeID'),
        ),
        migrations.AlterUniqueTogether(
            name='batchtypebatchprocesstype',
            unique_together={('batch_type_id', 'batch_process_type_id')},
        ),
    ]
