# Generated by Django 2.0.5 on 2018-05-25 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('batch_process', '0006_auto_20180525_2158'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchProcess',
            fields=[
                ('batch_process_id', models.BigAutoField(db_column='batch_process_id', primary_key=True, serialize=False, verbose_name='BatchProcessID')),
                ('batch_process_type_id', models.ForeignKey(db_column='batch_process_type_id', default=0, on_delete=django.db.models.deletion.PROTECT, to='batch_process.BatchProcessType', verbose_name='BatchProcessTypeID')),
            ],
            options={
                'db_table': 'batch_process',
            },
        ),
    ]
