# Generated by Django 2.1.3 on 2019-02-10 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch_process', '0006_batchprocess_batch_process_type_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchprocess',
            name='batch_process_tag',
            field=models.CharField(blank=True, db_column='batch_process_tag', default='', max_length=50, verbose_name='BatchProcessTag'),
        ),
        migrations.AddField(
            model_name='batchprocess',
            name='test_instance',
            field=models.BooleanField(db_column='test_instance', default=False, verbose_name='TestInstance'),
        ),
    ]
