# Generated by Django 2.0.5 on 2018-05-25 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch_process', '0007_batchprocess'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchprocess',
            name='description',
            field=models.CharField(blank=True, db_column='description', default='', max_length=100, verbose_name='Description'),
        ),
    ]
