# Generated by Django 2.0.5 on 2018-05-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch_process', '0008_batchprocess_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchprocess',
            name='test_instance',
            field=models.BooleanField(db_column='test_instance', default=False, verbose_name='TestInstance'),
        ),
    ]
