# Generated by Django 2.1.3 on 2019-02-10 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch_process', '0009_auto_20190210_1841'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchProcessJsonData',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'batch_process_json_data',
            },
        ),
    ]
