# Generated by Django 2.0.5 on 2018-05-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch_process', '0009_batchprocess_test_instance'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchprocess',
            name='process_status',
            field=models.SmallIntegerField(choices=[(0, 'Pending'), (1, 'Running'), (2, 'Finished'), (-1, 'Aborted'), (-2, 'Cancelling...'), (-3, 'Cancelled')], db_column='process_status', default=0, verbose_name='ProcessStatus'),
        ),
    ]
