# Generated by Django 2.1.3 on 2019-02-10 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('json_data', '0004_auto_20190210_1609'),
        ('batch_process', '0010_batchprocessjsondata'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchprocessjsondata',
            name='batch_process_id',
            field=models.ForeignKey(db_column='batch_process_id', default=0, on_delete=django.db.models.deletion.CASCADE, to='batch_process.BatchProcess', verbose_name='BatchProcessID'),
        ),
        migrations.AddField(
            model_name='batchprocessjsondata',
            name='json_data_id',
            field=models.ForeignKey(db_column='json_data_id', default=0, on_delete=django.db.models.deletion.CASCADE, to='json_data.JsonData', verbose_name='JsonDataID'),
        ),
        migrations.AlterUniqueTogether(
            name='batchprocessjsondata',
            unique_together={('batch_process_id', 'json_data_id')},
        ),
    ]
