# Generated by Django 2.0.5 on 2018-05-26 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('json_data', '0026_delete_jsondatasettype'),
        ('batch_process', '0011_auto_20180526_1658'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchProcessJsonData',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_process_id', models.ForeignKey(db_column='batch_process_id', default=0, on_delete=django.db.models.deletion.CASCADE, to='batch_process.BatchProcess', verbose_name='BatchProcessID')),
                ('json_data_id', models.ForeignKey(db_column='json_data_id', default=0, on_delete=django.db.models.deletion.CASCADE, to='json_data.JsonData', verbose_name='JsonDataID')),
            ],
            options={
                'db_table': 'batch_process_json_data',
            },
        ),
        migrations.AlterField(
            model_name='batchtypebatchprocesstype',
            name='batch_process_type_id',
            field=models.ForeignKey(db_column='batch_process_type_id', default=0, on_delete=django.db.models.deletion.PROTECT, to='batch_process.BatchProcessType', verbose_name='BatchProcessTypeID'),
        ),
        migrations.AlterField(
            model_name='batchtypebatchprocesstype',
            name='batch_type_id',
            field=models.ForeignKey(db_column='batch_type_id', default=0, on_delete=django.db.models.deletion.PROTECT, to='batch_process.BatchType', verbose_name='BatchTypeID'),
        ),
        migrations.AlterUniqueTogether(
            name='batchprocessjsondata',
            unique_together={('batch_process_id', 'json_data_id')},
        ),
    ]
