# Generated by Django 2.1.3 on 2019-02-10 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch_process', '0012_batchprocessjsondata_created_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchProcessLog',
            fields=[
                ('batch_process_log_id', models.BigAutoField(db_column='batch_process_log_id', primary_key=True, serialize=False, verbose_name='BatchProcessLogID')),
            ],
            options={
                'db_table': 'batch_process_log',
            },
        ),
    ]
