# Generated by Django 2.0.5 on 2018-05-26 20:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('batch_process', '0012_auto_20180526_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchprocessjsondata',
            name='created_timestamp',
            field=models.DateTimeField(db_column='created_timestamp', default=django.utils.timezone.now, verbose_name='Created'),
        ),
    ]
