# Generated by Django 2.0.5 on 2018-05-26 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('batch_process', '0013_batchprocessjsondata_created_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchProcessLog',
            fields=[
                ('batch_process_log_id', models.BigAutoField(db_column='batch_process_log_id', primary_key=True, serialize=False, verbose_name='BatchProcessLogID')),
                ('batch_process_id', models.ForeignKey(db_column='batch_process_id', default=0, on_delete=django.db.models.deletion.CASCADE, to='batch_process.BatchProcess', verbose_name='BatchProcessID')),
            ],
            options={
                'db_table': 'batch_process_log',
            },
        ),
    ]
