# Generated by Django 2.1.3 on 2019-02-10 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch_process', '0014_batchprocesslog_batch_process_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchprocesslog',
            name='process_operation',
            field=models.SmallIntegerField(blank=True, choices=[(-1, 'Cancel'), (0, '<None>'), (1, 'Run'), (2, 'Resume'), (3, 'ReRun Errors'), (4, 'ReRun All')], db_column='process_operation', null=True, verbose_name='ProcessOperation'),
        ),
    ]
