# Generated by Django 2.0.5 on 2018-05-26 20:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('batch_process', '0015_batchprocesslog_process_operation'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchprocesslog',
            name='log_timestamp',
            field=models.DateTimeField(db_column='log_timestamp', default=django.utils.timezone.now, verbose_name='TimeStamp'),
        ),
    ]
