# Generated by Django 2.1.3 on 2019-02-10 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batch_process', '0015_batchprocesslog_process_operation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchprocesslog',
            name='process_operation',
        ),
    ]
