# Generated by Django 2.1.3 on 2019-02-10 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch_process', '0016_remove_batchprocesslog_process_operation'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchprocesslog',
            name='process_action',
            field=models.SmallIntegerField(blank=True, choices=[(-1, 'Cancel'), (0, '<None>'), (1, 'Run'), (2, 'Resume'), (3, 'ReRun Errors'), (4, 'ReRun All')], db_column='process_action', null=True, verbose_name='ProcessAction'),
        ),
    ]
