# Generated by Django 2.0.5 on 2018-05-26 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch_process', '0016_batchprocesslog_log_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchprocesslog',
            name='log_entry_type',
            field=models.CharField(choices=[('DEBUG', 'Debug'), ('TRACE', 'Trace'), ('INFO', 'Informational'), ('WARN', 'Warning'), ('ERROR', 'Error'), ('FATAL', 'Fatal')], db_column='log_entry_type', default='INFO', max_length=5, verbose_name='Type'),
        ),
    ]
