# Generated by Django 2.0.5 on 2018-05-26 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch_process', '0017_batchprocesslog_log_entry_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchprocesslog',
            name='log_message',
            field=models.TextField(db_column='log_message', default='', verbose_name='Log Message'),
        ),
    ]
