# Generated by Django 2.1.3 on 2019-02-10 20:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('batch_process', '0017_batchprocesslog_process_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchprocesslog',
            name='log_timestamp',
            field=models.DateTimeField(db_column='log_timestamp', default=django.utils.timezone.now, verbose_name='TimeStamp'),
        ),
    ]
