# Generated by Django 2.1.3 on 2019-02-10 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch_process', '0018_batchprocesslog_log_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchprocesslog',
            name='log_entry_type',
            field=models.CharField(choices=[('DEBUG', 'Debug'), ('TRACE', 'Trace'), ('INFO', 'Informational'), ('WARN', 'Warning'), ('ERROR', 'Error'), ('FATAL', 'Fatal')], db_column='log_entry_type', default='INFO', max_length=5, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='batchprocesslog',
            name='log_message',
            field=models.TextField(db_column='log_message', default='', verbose_name='Log Message'),
        ),
    ]
