# Generated by Django 2.0.5 on 2018-05-26 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('batch_process', '0018_batchprocesslog_log_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchProcessTask',
            fields=[
                ('batch_process_task_id', models.BigAutoField(db_column='batch_process_task_id', primary_key=True, serialize=False, verbose_name='BatchProcessTaskID')),
                ('task_number', models.IntegerField(db_column='task_number', default=0, verbose_name='TaskNumber')),
                ('batch_process_id', models.ForeignKey(db_column='batch_process_id', default=0, on_delete=django.db.models.deletion.CASCADE, to='batch_process.BatchProcess', verbose_name='BatchProcessID')),
            ],
            options={
                'db_table': 'batch_process_task',
            },
        ),
        migrations.AlterUniqueTogether(
            name='batchprocesstask',
            unique_together={('batch_process_id', 'task_number')},
        ),
    ]
