# Generated by Django 2.1.3 on 2019-02-10 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch_process', '0019_auto_20190210_2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchProcessTask',
            fields=[
                ('batch_process_task_id', models.BigAutoField(db_column='batch_process_task_id', primary_key=True, serialize=False, verbose_name='BatchProcessTaskID')),
            ],
            options={
                'db_table': 'batch_process_task',
            },
        ),
    ]
