# Generated by Django 2.0.5 on 2018-05-26 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batch_process', '0019_auto_20180526_2211'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='batchprocesstask',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='batchprocesstask',
            name='task_number',
        ),
    ]
