# Generated by Django 2.0.5 on 2018-05-26 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch_process', '0020_auto_20180526_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchprocesstask',
            name='task_number',
            field=models.IntegerField(db_column='task_number', default=0, verbose_name='TaskNumber'),
        ),
        migrations.AlterUniqueTogether(
            name='batchprocesstask',
            unique_together={('batch_process_id', 'task_number')},
        ),
    ]
