# Generated by Django 2.1.3 on 2019-02-10 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('batch_process', '0020_batchprocesstask'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchprocesstask',
            name='batch_process_id',
            field=models.ForeignKey(db_column='batch_process_id', default=0, on_delete=django.db.models.deletion.CASCADE, to='batch_process.BatchProcess', verbose_name='BatchProcessID'),
        ),
        migrations.AddField(
            model_name='batchprocesstask',
            name='task_number',
            field=models.PositiveIntegerField(db_column='task_number', default=0, verbose_name='TaskNumber'),
        ),
        migrations.AlterUniqueTogether(
            name='batchprocesstask',
            unique_together={('batch_process_id', 'task_number')},
        ),
    ]
