# Generated by Django 2.0.5 on 2018-05-26 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch_process', '0023_batchprocesstask_run_finish_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchprocesstask',
            name='task_number',
            field=models.PositiveIntegerField(db_column='task_number', default=0, verbose_name='TaskNumber'),
        ),
    ]
