# Generated by Django 2.0.5 on 2018-05-26 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch_process', '0024_auto_20180526_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchprocesstask',
            name='run_done_items',
            field=models.PositiveIntegerField(blank=True, db_column='run_done_items', null=True, verbose_name='Done'),
        ),
        migrations.AddField(
            model_name='batchprocesstask',
            name='run_total_items',
            field=models.PositiveIntegerField(blank=True, db_column='run_total_items', null=True, verbose_name='Total'),
        ),
    ]
