# Generated by Django 2.1.3 on 2019-02-10 20:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('batch_process', '0024_auto_20190210_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchprocesstask',
            name='created_timestamp',
            field=models.DateTimeField(db_column='created_timestamp', default=django.utils.timezone.now, verbose_name='Created'),
        ),
        migrations.AddField(
            model_name='batchprocesstask',
            name='updated_timestamp',
            field=models.DateTimeField(blank=True, db_column='updated_timestamp', default=django.utils.timezone.now, null=True, verbose_name='Updated'),
        ),
    ]
