# Generated by Django 2.1.3 on 2019-02-10 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batch_process', '0026_batchprocesstasklog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BatchProcessTaskLog',
        ),
    ]
