# Generated by Django 2.0.5 on 2018-05-26 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batch_process', '0027_batchprocesstaskinterventionlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchprocesstaskinterventionlog',
            name='intervention_timestamp',
        ),
    ]
