# Generated by Django 2.0.5 on 2018-05-26 21:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('batch_process', '0028_remove_batchprocesstaskinterventionlog_intervention_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchprocesstaskinterventionlog',
            name='intervention_timestamp',
            field=models.DateTimeField(db_column='intervention_timestamp', default=django.utils.timezone.now, verbose_name='TimeStamp'),
        ),
    ]
