# Generated by Django 2.1.3 on 2019-02-10 20:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('batch_process', '0028_batchprocesstaskintervention'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchprocesstaskintervention',
            name='batch_process_task_id',
            field=models.ForeignKey(db_column='batch_process_task_id', default=0, on_delete=django.db.models.deletion.CASCADE, to='batch_process.BatchProcessTask', verbose_name='BatchProcessTaskID'),
        ),
        migrations.AddField(
            model_name='batchprocesstaskintervention',
            name='intervention_timestamp',
            field=models.DateTimeField(db_column='log_timestamp', default=django.utils.timezone.now, verbose_name='TimeStamp'),
        ),
        migrations.AddField(
            model_name='batchprocesstaskintervention',
            name='intervention_type',
            field=models.SmallIntegerField(choices=[(-1, 'Cancelled'), (0, '<None>'), (1, 'Resumed')], db_column='intervention_type', default=0, verbose_name='InterventionType'),
        ),
    ]
