# Generated by Django 2.1.3 on 2019-02-10 20:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('batch_process', '0029_auto_20190210_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchprocesstaskintervention',
            name='intervention_timestamp',
            field=models.DateTimeField(db_column='intervention_timestamp', default=django.utils.timezone.now, verbose_name='TimeStamp'),
        ),
    ]
