# Generated by Django 2.0.5 on 2018-05-26 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch_process', '0029_batchprocesstaskinterventionlog_intervention_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchprocesstaskinterventionlog',
            name='intervention_type',
            field=models.SmallIntegerField(choices=[(-1, 'Cancelled'), (0, '<None>'), (1, 'Resumed')], db_column='intervention_type', default=0, verbose_name='InterventionType'),
        ),
    ]
