# Generated by Django 2.0.5 on 2018-05-26 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batch_process', '0030_batchprocesstaskinterventionlog_intervention_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchprocesstaskinterventionlog',
            name='batch_process_task_id',
        ),
        migrations.DeleteModel(
            name='BatchProcessTaskInterventionLog',
        ),
    ]
