# Generated by Django 2.1.3 on 2019-02-11 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batch_process', '0030_auto_20190210_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchprocess',
            name='created_timestamp',
        ),
        migrations.RemoveField(
            model_name='batchprocess',
            name='updated_timestamp',
        ),
    ]
