# Generated by Django 2.0.5 on 2018-05-26 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('batch_process', '0031_auto_20180526_2250'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchProcessTaskLog',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_process_task_id', models.ForeignKey(db_column='batch_process_task_id', default=0, on_delete=django.db.models.deletion.CASCADE, to='batch_process.BatchProcessTask', verbose_name='BatchProcessTaskID')),
            ],
            options={
                'db_table': 'batch_process_task_log',
            },
        ),
    ]
