# Generated by Django 2.1.3 on 2019-02-11 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('json_data', '0008_auto_20190211_2129'),
        ('batch_process', '0031_auto_20190211_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchprocess',
            name='json_data_id',
            field=models.ForeignKey(db_column='json_data_id', default=0, on_delete=django.db.models.deletion.PROTECT, to='json_data.JsonData', verbose_name='JsonDataID'),
        ),
    ]
