# Generated by Django 2.0.5 on 2018-05-26 21:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('batch_process', '0032_batchprocesstasklog'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchprocesstasklog',
            name='intervention_timestamp',
            field=models.DateTimeField(db_column='intervention_timestamp', default=django.utils.timezone.now, verbose_name='TimeStamp'),
        ),
    ]
