# Generated by Django 2.1.3 on 2019-02-11 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batch_process', '0033_auto_20190211_2151'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='batchprocessjsondata',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='batchprocessjsondata',
            name='batch_process_id',
        ),
        migrations.RemoveField(
            model_name='batchprocessjsondata',
            name='json_data_id',
        ),
        migrations.DeleteModel(
            name='BatchProcessJsonData',
        ),
    ]
