# Generated by Django 2.0.5 on 2018-05-26 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('batch_process', '0034_batchprocesstasklog_intervention_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batchprocesstasklog',
            name='intervention_timestamp',
        ),
        migrations.RemoveField(
            model_name='batchprocesstasklog',
            name='intervention_type',
        ),
    ]
