# Generated by Django 2.0.5 on 2018-05-26 21:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('batch_process', '0035_auto_20180526_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchprocesstasklog',
            name='log_timestamp',
            field=models.DateTimeField(db_column='log_timestamp', default=django.utils.timezone.now, verbose_name='TimeStamp'),
        ),
    ]
