# Generated by Django 2.0.5 on 2018-05-26 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch_process', '0036_batchprocesstasklog_log_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchprocesstasklog',
            name='intervention_type',
            field=models.SmallIntegerField(choices=[(-1, 'Cancelled'), (0, '<None>'), (1, 'Resumed')], db_column='intervention_type', default=0, verbose_name='InterventionType'),
        ),
    ]
