# Generated by Django 3.1 on 2020-09-15 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch_process', '0037_batchprocesstaskintervention_intervention_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchprocesstype',
            name='configuration',
            field=models.JSONField(blank=True, db_column='configuration', null=True, verbose_name='Configuration'),
        ),
    ]
