# Generated by Django 2.1.3 on 2018-11-19 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemDataType',
            fields=[
                ('system_data_type', models.SmallIntegerField(db_column='system_data_type', primary_key=True, serialize=False, verbose_name='SystemDataType')),
                ('description', models.CharField(db_column='description', default='', max_length=250, unique=True, verbose_name='Description')),
                ('notes', models.CharField(blank=True, db_column='notes', default='', max_length=1000, verbose_name='Notes')),
            ],
            options={
                'db_table': 'system_data_type',
            },
        ),
        migrations.CreateModel(
            name='SystemDataTypeMapping',
            fields=[
                ('database_data_type', models.CharField(db_column='database_data_type', max_length=63, primary_key=True, serialize=False, verbose_name='Database DataType')),
                ('system_data_type', models.ForeignKey(db_column='system_data_type', default=0, on_delete=django.db.models.deletion.PROTECT, to='system.SystemDataType', verbose_name='SystemDataType')),
            ],
            options={
                'db_table': 'system_data_type_mapping',
            },
        ),
    ]
