# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemDataType',
            fields=[
                ('system_data_type', models.SmallIntegerField(db_column='system_data_type', primary_key=True, serialize=False, verbose_name='SystemDataType')),
                ('description', models.CharField(db_column='description', default='', max_length=100, unique=True, verbose_name='Description')),
                ('notes', models.CharField(blank=True, db_column='notes', max_length=250, null=True, verbose_name='Notes')),
            ],
            options={
                'db_table': 'system_data_type',
            },
        ),
    ]
