# Generated by Django 2.1.3 on 2018-11-19 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemAuditRecord',
            fields=[
                ('audit_id', models.BigAutoField(db_column='audit_id', primary_key=True, serialize=False, verbose_name='AuditID')),
            ],
            options={
                'db_table': 'system_audit_record',
            },
        ),
    ]
