# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 20:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemDataTypeMapping',
            fields=[
                ('database_data_type', models.CharField(db_column='database_data_type', max_length=63, primary_key=True, serialize=False, verbose_name='Database DataType')),
                ('system_data_type', models.ForeignKey(db_column='system_data_type', default=0, on_delete=django.db.models.deletion.PROTECT, to='system.SystemDataType', verbose_name='SystemDataType')),
            ],
            options={
                'db_table': 'system_data_type_mapping',
            },
        ),
    ]
