# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 20:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_systemdatatypemapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemAuditRecord',
            fields=[
                ('audit_id', models.BigAutoField(db_column='audit_id', primary_key=True, serialize=False, verbose_name='AuditID')),
                ('audit_action', models.CharField(choices=[('-', 'None'), ('I', 'Insert'), ('U', 'Update'), ('D', 'Delete')], db_column='audit_action', default='-', max_length=1, verbose_name='Audit Action')),
                ('audit_timestamp', models.DateTimeField(db_column='audit_timestamp', default=django.utils.timezone.now, verbose_name='Audit Timestamp')),
                ('table_name', models.CharField(db_column='table_name', default='', max_length=63, verbose_name='Table Name')),
            ],
            options={
                'db_table': 'system_audit_record',
            },
        ),
    ]
