# Generated by Django 2.1.3 on 2018-11-19 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_auto_20181119_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemauditrecord',
            name='table_name',
            field=models.CharField(db_column='table_name', default='', max_length=63, verbose_name='Table Name'),
        ),
    ]
