# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_systemauditrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemauditrecord',
            name='primary_key_field_name',
            field=models.CharField(db_column='primary_key_field_name', default='', max_length=63, verbose_name='Primary Key Field'),
        ),
        migrations.AddField(
            model_name='systemauditrecord',
            name='primary_key_field_value',
            field=models.TextField(db_column='primary_key_field_value', default='', verbose_name='Primary Key Value'),
        ),
    ]
