# Generated by Django 2.1.3 on 2018-11-19 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_systemauditrecord_table_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemauditrecord',
            name='primary_key_field_name',
            field=models.CharField(db_column='primary_key_field_name', default='', max_length=63, verbose_name='Primary Key Field'),
        ),
    ]
