# Generated by Django 2.1.3 on 2018-11-19 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_systemauditrecord_primary_key_field_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemauditrecord',
            name='primary_key_field_value',
            field=models.BigIntegerField(db_column='primary_key_field_value', default=0, verbose_name='Primary Key Value'),
        ),
    ]
