# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 20:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_systemauditrecord_field_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemauditrecord',
            name='field_data_type',
            field=models.ForeignKey(db_column='field_data_type', default=0, on_delete=django.db.models.deletion.PROTECT, to='system.SystemDataType', verbose_name='Field DataType'),
        ),
        migrations.AddField(
            model_name='systemauditrecord',
            name='field_value_boolean',
            field=models.NullBooleanField(db_column='field_value_boolean', verbose_name='Boolean'),
        ),
        migrations.AddField(
            model_name='systemauditrecord',
            name='field_value_integer',
            field=models.BigIntegerField(blank=True, db_column='field_value_integer', null=True, verbose_name='Integer'),
        ),
    ]
