# Generated by Django 2.1.3 on 2018-11-19 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_systemauditrecord_primary_key_field_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemauditrecord',
            name='field_name',
            field=models.CharField(db_column='field_name', default='', max_length=63, verbose_name='Field Name'),
        ),
    ]
