# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_auto_20170913_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemauditrecord',
            name='field_value_float',
            field=models.FloatField(blank=True, db_column='field_value_float', null=True, verbose_name='Float'),
        ),
    ]
