# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_systemauditrecord_field_value_float'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemauditrecord',
            name='field_value_decimal',
            field=models.DecimalField(blank=True, db_column='field_value_decimal', decimal_places=50, max_digits=100, null=True, verbose_name='Decimal'),
        ),
    ]
