# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_systemauditrecord_field_value_decimal'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemauditrecord',
            name='field_value_date',
            field=models.DateField(blank=True, db_column='field_value_date', null=True, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='systemauditrecord',
            name='field_value_time',
            field=models.TimeField(blank=True, db_column='field_value_time', null=True, verbose_name='Time'),
        ),
    ]
