# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_auto_20170913_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemauditrecord',
            name='field_value_datetime',
            field=models.DateTimeField(blank=True, db_column='field_value_datetime', null=True, verbose_name='DateTime'),
        ),
        migrations.AddField(
            model_name='systemauditrecord',
            name='field_value_duration',
            field=models.DurationField(blank=True, db_column='field_value_duration', null=True, verbose_name='Duration'),
        ),
        migrations.AddField(
            model_name='systemauditrecord',
            name='field_value_text',
            field=models.TextField(blank=True, db_column='field_value_text', null=True, verbose_name='Text'),
        ),
    ]
