# Generated by Django 2.1.3 on 2018-11-19 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0010_systemauditrecord_field_value_integer'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemauditrecord',
            name='field_value_float',
            field=models.FloatField(blank=True, db_column='field_value_float', null=True, verbose_name='Float'),
        ),
    ]
