# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 20:48
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0010_auto_20170913_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemauditrecord',
            name='field_value_json',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, db_column='field_value_json', null=True, verbose_name='JSON'),
        ),
    ]
