# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0011_systemauditrecord_field_value_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemauditrecord',
            name='field_value_blob',
            field=models.BinaryField(blank=True, db_column='field_value_blob', null=True, verbose_name='BLOB'),
        ),
    ]
