# Generated by Django 2.1.3 on 2018-11-19 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0011_systemauditrecord_field_value_float'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemauditrecord',
            name='field_value_decimal',
            field=models.DecimalField(blank=True, db_column='field_value_decimal', decimal_places=500, max_digits=1000, null=True, verbose_name='Decimal'),
        ),
    ]
