# Generated by Django 2.0.5 on 2018-05-11 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0012_systemauditrecord_field_value_blob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemdatatype',
            name='notes',
            field=models.CharField(blank=True, db_column='notes', default='', max_length=250, verbose_name='Notes'),
        ),
    ]
