# Generated by Django 2.1.3 on 2018-11-19 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0012_systemauditrecord_field_value_decimal'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemauditrecord',
            name='field_value_date',
            field=models.DateField(blank=True, db_column='field_value_date', null=True, verbose_name='Date'),
        ),
    ]
