# Generated by Django 2.1.3 on 2018-11-19 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0013_systemauditrecord_field_value_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemauditrecord',
            name='field_value_time',
            field=models.TimeField(blank=True, db_column='field_value_time', null=True, verbose_name='Time'),
        ),
    ]
