# Generated by Django 2.1.3 on 2018-11-19 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0014_systemauditrecord_field_value_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemauditrecord',
            name='field_value_datetime',
            field=models.DateTimeField(blank=True, db_column='field_value_datetime', null=True, verbose_name='DateTime'),
        ),
    ]
