# Generated by Django 2.1.3 on 2018-11-22 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0019_systemauditrecord_field_value_blob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemauditrecord',
            name='field_data_type',
        ),
        migrations.DeleteModel(
            name='SystemAuditRecord',
        ),
    ]
