# Generated by Django 2.1.3 on 2018-11-22 21:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0021_systemauditrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemauditrecord',
            name='audit_action',
            field=models.SmallIntegerField(choices=[(1, 'Insert'), (0, 'Update'), (-1, 'Delete')], db_column='audit_action', default=0, verbose_name='Audit Action'),
        ),
        migrations.AddField(
            model_name='systemauditrecord',
            name='audit_timestamp',
            field=models.DateTimeField(db_column='audit_timestamp', default=django.utils.timezone.now, verbose_name='Audit Timestamp'),
        ),
        migrations.AddField(
            model_name='systemauditrecord',
            name='table_name',
            field=models.CharField(db_column='table_name', default='', max_length=63, verbose_name='Table Name'),
        ),
    ]
