# Generated by Django 2.1.3 on 2018-11-22 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0022_auto_20181122_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemauditrecord',
            name='primary_key_field_name',
            field=models.CharField(db_column='primary_key_field_name', default='', max_length=63, verbose_name='Primary Key Field'),
        ),
        migrations.AddField(
            model_name='systemauditrecord',
            name='primary_key_field_value',
            field=models.BigIntegerField(db_column='primary_key_field_value', default=0, verbose_name='Primary Key Value'),
        ),
    ]
