# Generated by Django 2.1.3 on 2018-11-22 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0023_auto_20181122_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemauditrecord',
            name='field_name',
            field=models.CharField(db_column='field_name', default='', max_length=63, verbose_name='Field Name'),
        ),
    ]
