# Generated by Django 2.1.3 on 2018-11-22 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0024_systemauditrecord_field_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemauditrecord',
            name='field_data_type',
            field=models.ForeignKey(db_column='field_data_type', default=0, on_delete=django.db.models.deletion.PROTECT, to='system.SystemDataType', verbose_name='Field DataType'),
        ),
    ]
