# Generated by Django 2.1.3 on 2018-11-22 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0026_auto_20181122_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemauditrecord',
            name='field_value_float',
            field=models.FloatField(blank=True, db_column='field_value_float', null=True, verbose_name='Float'),
        ),
    ]
