# Generated by Django 2.1.3 on 2018-11-23 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0034_auto_20181122_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemauditrecord',
            name='field_data_type',
            field=models.SmallIntegerField(choices=[(0, 'None'), (1, 'Boolean'), (2, 'Integer'), (3, 'Float'), (4, 'Decimal'), (5, 'Date'), (6, 'Time'), (7, 'DateTime'), (8, 'Duration'), (9, 'Text'), (10, 'JSON'), (11, 'BLOB')], db_column='field_data_type', default=0, verbose_name='Field DataType'),
        ),
    ]
