# Generated by Django 2.1.3 on 2018-11-24 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0035_auto_20181123_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemdatatypemapping',
            name='system_data_type',
        ),
        migrations.DeleteModel(
            name='SystemDataType',
        ),
        migrations.DeleteModel(
            name='SystemDataTypeMapping',
        ),
    ]
