# Generated by Django 3.1 on 2020-09-15 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0036_auto_20181124_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemauditrecord',
            name='field_value_boolean',
            field=models.BooleanField(blank=True, db_column='field_value_boolean', null=True, verbose_name='Boolean'),
        ),
        migrations.AlterField(
            model_name='systemauditrecord',
            name='field_value_json',
            field=models.JSONField(blank=True, db_column='field_value_json', null=True, verbose_name='JSON'),
        ),
    ]
